/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package n;

import com.github.xpenatan.webgpu.*;

final public class n1446294037 {

    public static native long n2287490261();

    public static native void n2781454729(long this_addr);

    public static native void n2667887140(long this_addr, long chainedStruct_addr);

    public static native void n606182092(long this_addr, int type);

    public static native long n1441072606();
}
