/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package n;

import com.github.xpenatan.webgpu.*;

final public class n1610067404 {

    static native public int n1475541554();

    static native public int n3779922630();

    static native public int n3810926096();

    static native public int n2626621364();
}
