/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package n;

import com.github.xpenatan.webgpu.*;

final public class n2232430437 {

    public static native long n1897896325();

    public static native void n1463929561(long this_addr);

    public static native void n1759737620(long this_addr, String label);

    public static native void n1562015444(long this_addr, long chainedStruct_addr);

    public static native void n478538766(long this_addr, long colorFormats_addr);

    public static native void n10669414(long this_addr, int depthStencilFormat);

    public static native void n3828010171(long this_addr, int sampleCount);

    public static native void n2554353339(long this_addr, int depthReadOnly);

    public static native void n486068130(long this_addr, int stencilReadOnly);

    public static native long n1051478670();
}
