/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package n;

import com.github.xpenatan.webgpu.*;

final public class n3847900688 {

    static native public int n296669812();

    static native public int n2101049588();

    static native public int n1623297895();

    static native public int n147601365();

    static native public int n4183000408();

    static native public int n4002564398();
}
