/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class WGPUDevice extends IDLBase {

    private WGPUQueue WGPUQueue_TEMP_GEN_0;

    static public final WGPUDevice NULL = WGPUDevice.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUDevice(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUDevice native_new() {
        return new WGPUDevice((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
delete nativeObject;
*/
    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void release() {
        internal_native_Release(native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
nativeObject->Release();
*/
    public static void internal_native_Release(long this_addr) {
        try {
            FFMHandles.internal_native_Release__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void createBindGroup(WGPUBindGroupDescriptor descriptor, WGPUBindGroup valueOut) {
        internal_native_CreateBindGroup(native_address, descriptor.native_address, valueOut.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
nativeObject->CreateBindGroup((JGPU::WGPUBindGroupDescriptor* )descriptor_addr, (JGPU::WGPUBindGroup* )valueOut_addr);
*/
    public static void internal_native_CreateBindGroup(long this_addr, long descriptor_addr, long valueOut_addr) {
        try {
            FFMHandles.internal_native_CreateBindGroup__JJJ.invokeExact(this_addr, descriptor_addr, valueOut_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void createBindGroupLayout(WGPUBindGroupLayoutDescriptor descriptor, WGPUBindGroupLayout valueOut) {
        internal_native_CreateBindGroupLayout(native_address, descriptor.native_address, valueOut.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
nativeObject->CreateBindGroupLayout((JGPU::WGPUBindGroupLayoutDescriptor* )descriptor_addr, (JGPU::WGPUBindGroupLayout* )valueOut_addr);
*/
    public static void internal_native_CreateBindGroupLayout(long this_addr, long descriptor_addr, long valueOut_addr) {
        try {
            FFMHandles.internal_native_CreateBindGroupLayout__JJJ.invokeExact(this_addr, descriptor_addr, valueOut_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public WGPUBuffer createBuffer(WGPUBufferDescriptor descriptor) {
        long addr = internal_native_CreateBuffer__0_addr(native_address, descriptor.native_address);
        if (addr == 0)
            return WGPUBuffer.NULL;
        WGPUBuffer WGPUBuffer_NEW = WGPUBuffer.native_new();
        WGPUBuffer_NEW.internal_reset(addr, true);
        return WGPUBuffer_NEW;
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
JGPU::WGPUBuffer* obj = nativeObject->CreateBuffer((JGPU::WGPUBufferDescriptor* )descriptor_addr);
return (int64_t)obj;
*/
    public static long internal_native_CreateBuffer__0_addr(long this_addr, long descriptor_addr) {
        try {
            return (long) FFMHandles.internal_native_CreateBuffer__0_addr__JJ.invokeExact(this_addr, descriptor_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void createBuffer(WGPUBufferDescriptor descriptor, WGPUBuffer valueOut) {
        internal_native_CreateBuffer__1(native_address, descriptor.native_address, valueOut.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
nativeObject->CreateBuffer((JGPU::WGPUBufferDescriptor* )descriptor_addr, (JGPU::WGPUBuffer* )valueOut_addr);
*/
    public static void internal_native_CreateBuffer__1(long this_addr, long descriptor_addr, long valueOut_addr) {
        try {
            FFMHandles.internal_native_CreateBuffer__1__JJJ.invokeExact(this_addr, descriptor_addr, valueOut_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void createCommandEncoder(WGPUCommandEncoderDescriptor descriptor, WGPUCommandEncoder valueOut) {
        internal_native_CreateCommandEncoder(native_address, descriptor.native_address, valueOut.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
nativeObject->CreateCommandEncoder((JGPU::WGPUCommandEncoderDescriptor* )descriptor_addr, (JGPU::WGPUCommandEncoder* )valueOut_addr);
*/
    public static void internal_native_CreateCommandEncoder(long this_addr, long descriptor_addr, long valueOut_addr) {
        try {
            FFMHandles.internal_native_CreateCommandEncoder__JJJ.invokeExact(this_addr, descriptor_addr, valueOut_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void createComputePipeline(WGPUComputePipelineDescriptor descriptor, WGPUComputePipeline valueOut) {
        internal_native_CreateComputePipeline(native_address, descriptor.native_address, valueOut.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
nativeObject->CreateComputePipeline((JGPU::WGPUComputePipelineDescriptor* )descriptor_addr, (JGPU::WGPUComputePipeline* )valueOut_addr);
*/
    public static void internal_native_CreateComputePipeline(long this_addr, long descriptor_addr, long valueOut_addr) {
        try {
            FFMHandles.internal_native_CreateComputePipeline__JJJ.invokeExact(this_addr, descriptor_addr, valueOut_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void createPipelineLayout(WGPUPipelineLayoutDescriptor descriptor, WGPUPipelineLayout valueOut) {
        internal_native_CreatePipelineLayout(native_address, descriptor.native_address, valueOut.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
nativeObject->CreatePipelineLayout((JGPU::WGPUPipelineLayoutDescriptor* )descriptor_addr, (JGPU::WGPUPipelineLayout* )valueOut_addr);
*/
    public static void internal_native_CreatePipelineLayout(long this_addr, long descriptor_addr, long valueOut_addr) {
        try {
            FFMHandles.internal_native_CreatePipelineLayout__JJJ.invokeExact(this_addr, descriptor_addr, valueOut_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void createQuerySet(WGPUQuerySetDescriptor descriptor, WGPUQuerySet valueOut) {
        internal_native_CreateQuerySet(native_address, descriptor.native_address, valueOut.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
nativeObject->CreateQuerySet((JGPU::WGPUQuerySetDescriptor* )descriptor_addr, (JGPU::WGPUQuerySet* )valueOut_addr);
*/
    public static void internal_native_CreateQuerySet(long this_addr, long descriptor_addr, long valueOut_addr) {
        try {
            FFMHandles.internal_native_CreateQuerySet__JJJ.invokeExact(this_addr, descriptor_addr, valueOut_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void createRenderBundleEncoder(WGPURenderBundleEncoderDescriptor descriptor, WGPURenderBundleEncoder valueOut) {
        internal_native_CreateRenderBundleEncoder(native_address, descriptor.native_address, valueOut.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
nativeObject->CreateRenderBundleEncoder((JGPU::WGPURenderBundleEncoderDescriptor* )descriptor_addr, (JGPU::WGPURenderBundleEncoder* )valueOut_addr);
*/
    public static void internal_native_CreateRenderBundleEncoder(long this_addr, long descriptor_addr, long valueOut_addr) {
        try {
            FFMHandles.internal_native_CreateRenderBundleEncoder__JJJ.invokeExact(this_addr, descriptor_addr, valueOut_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void createRenderPipeline(WGPURenderPipelineDescriptor descriptor, WGPURenderPipeline valueOut) {
        internal_native_CreateRenderPipeline(native_address, descriptor.native_address, valueOut.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
nativeObject->CreateRenderPipeline((JGPU::WGPURenderPipelineDescriptor* )descriptor_addr, (JGPU::WGPURenderPipeline* )valueOut_addr);
*/
    public static void internal_native_CreateRenderPipeline(long this_addr, long descriptor_addr, long valueOut_addr) {
        try {
            FFMHandles.internal_native_CreateRenderPipeline__JJJ.invokeExact(this_addr, descriptor_addr, valueOut_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void createSampler(WGPUSamplerDescriptor descriptor, WGPUSampler valueOut) {
        internal_native_CreateSampler(native_address, descriptor.native_address, valueOut.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
nativeObject->CreateSampler((JGPU::WGPUSamplerDescriptor* )descriptor_addr, (JGPU::WGPUSampler* )valueOut_addr);
*/
    public static void internal_native_CreateSampler(long this_addr, long descriptor_addr, long valueOut_addr) {
        try {
            FFMHandles.internal_native_CreateSampler__JJJ.invokeExact(this_addr, descriptor_addr, valueOut_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void createShaderModule(WGPUShaderModuleDescriptor descriptor, WGPUShaderModule shaderModule) {
        internal_native_CreateShaderModule(native_address, descriptor.native_address, shaderModule.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
nativeObject->CreateShaderModule((JGPU::WGPUShaderModuleDescriptor* )descriptor_addr, (JGPU::WGPUShaderModule* )shaderModule_addr);
*/
    public static void internal_native_CreateShaderModule(long this_addr, long descriptor_addr, long shaderModule_addr) {
        try {
            FFMHandles.internal_native_CreateShaderModule__JJJ.invokeExact(this_addr, descriptor_addr, shaderModule_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void createTexture(WGPUTextureDescriptor descriptor, WGPUTexture valueOut) {
        internal_native_CreateTexture(native_address, descriptor.native_address, valueOut.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
nativeObject->CreateTexture((JGPU::WGPUTextureDescriptor* )descriptor_addr, (JGPU::WGPUTexture* )valueOut_addr);
*/
    public static void internal_native_CreateTexture(long this_addr, long descriptor_addr, long valueOut_addr) {
        try {
            FFMHandles.internal_native_CreateTexture__JJJ.invokeExact(this_addr, descriptor_addr, valueOut_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void destroy() {
        internal_native_Destroy(native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
nativeObject->Destroy();
*/
    public static void internal_native_Destroy(long this_addr) {
        try {
            FFMHandles.internal_native_Destroy__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void getFeatures(WGPUSupportedFeatures features) {
        internal_native_GetFeatures(native_address, features.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
nativeObject->GetFeatures((JGPU::WGPUSupportedFeatures* )features_addr);
*/
    public static void internal_native_GetFeatures(long this_addr, long features_addr) {
        try {
            FFMHandles.internal_native_GetFeatures__JJ.invokeExact(this_addr, features_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public boolean hasFeature(WGPUFeatureName feature) {
        return internal_native_HasFeature(native_address, feature.getValue());
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
return nativeObject->HasFeature((::WGPUFeatureName)feature);
*/
    public static boolean internal_native_HasFeature(long this_addr, int feature) {
        try {
            return (boolean) FFMHandles.internal_native_HasFeature__JI.invokeExact(this_addr, feature);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void getLimits(WGPULimits limits) {
        internal_native_GetLimits(native_address, limits.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
nativeObject->GetLimits((JGPU::WGPULimits* )limits_addr);
*/
    public static void internal_native_GetLimits(long this_addr, long limits_addr) {
        try {
            FFMHandles.internal_native_GetLimits__JJ.invokeExact(this_addr, limits_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public WGPUQueue getQueue() {
        long addr = internal_native_GetQueue_addr(native_address);
        if (addr == 0)
            return WGPUQueue.NULL;
        if (WGPUQueue_TEMP_GEN_0 == null)
            WGPUQueue_TEMP_GEN_0 = WGPUQueue.native_new();
        WGPUQueue_TEMP_GEN_0.internal_reset(addr, false);
        return WGPUQueue_TEMP_GEN_0;
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUDevice* nativeObject = (JGPU::WGPUDevice*)this_addr;
JGPU::WGPUQueue* obj = nativeObject->GetQueue();
return (int64_t)obj;
*/
    public static long internal_native_GetQueue_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetQueue_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP;

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static {
            LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();
        }

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1deleteNative__J").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Release__J = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1Release__J").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateBindGroup__JJJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1CreateBindGroup__JJJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateBindGroupLayout__JJJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1CreateBindGroupLayout__JJJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateBuffer__0_addr__JJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1CreateBuffer_1_10_1addr__JJ").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateBuffer__1__JJJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1CreateBuffer_1_11__JJJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateCommandEncoder__JJJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1CreateCommandEncoder__JJJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateComputePipeline__JJJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1CreateComputePipeline__JJJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreatePipelineLayout__JJJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1CreatePipelineLayout__JJJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateQuerySet__JJJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1CreateQuerySet__JJJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateRenderBundleEncoder__JJJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1CreateRenderBundleEncoder__JJJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateRenderPipeline__JJJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1CreateRenderPipeline__JJJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateSampler__JJJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1CreateSampler__JJJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateShaderModule__JJJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1CreateShaderModule__JJJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CreateTexture__JJJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1CreateTexture__JJJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Destroy__J = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1Destroy__J").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetFeatures__JJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1GetFeatures__JJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_HasFeature__JI = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1HasFeature__JI").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_GetLimits__JJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1GetLimits__JJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetQueue_addr__J = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUDevice_internal_1native_1GetQueue_1addr__J").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
