/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUPowerPreference implements IDLEnum<WGPUPowerPreference> {

    CUSTOM(0), Undefined(WGPUPowerPreference_Undefined_NATIVE()), LowPower(WGPUPowerPreference_LowPower_NATIVE()), HighPerformance(WGPUPowerPreference_HighPerformance_NATIVE()), Force32(WGPUPowerPreference_Force32_NATIVE());

    private int value;

    private WGPUPowerPreference(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUPowerPreference setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUPowerPreference getCustom() {
        return CUSTOM;
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUPowerPreference_Undefined;
*/
    private static int WGPUPowerPreference_Undefined_NATIVE() {
        try {
            return (int) FFMHandles.WGPUPowerPreference_Undefined_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUPowerPreference_LowPower;
*/
    private static int WGPUPowerPreference_LowPower_NATIVE() {
        try {
            return (int) FFMHandles.WGPUPowerPreference_LowPower_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUPowerPreference_HighPerformance;
*/
    private static int WGPUPowerPreference_HighPerformance_NATIVE() {
        try {
            return (int) FFMHandles.WGPUPowerPreference_HighPerformance_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUPowerPreference_Force32;
*/
    private static int WGPUPowerPreference_Force32_NATIVE() {
        try {
            return (int) FFMHandles.WGPUPowerPreference_Force32_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP;

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static {
            LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();
        }

        static final java.lang.invoke.MethodHandle WGPUPowerPreference_Undefined_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUPowerPreference_WGPUPowerPreference_1Undefined_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUPowerPreference_LowPower_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUPowerPreference_WGPUPowerPreference_1LowPower_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUPowerPreference_HighPerformance_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUPowerPreference_WGPUPowerPreference_1HighPerformance_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUPowerPreference_Force32_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUPowerPreference_WGPUPowerPreference_1Force32_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
