/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class WGPUComputePassTimestampWrites extends IDLBase {

    static private WGPUComputePassTimestampWrites WGPUComputePassTimestampWrites_TEMP_STATIC_GEN_0;

    static public final WGPUComputePassTimestampWrites NULL = WGPUComputePassTimestampWrites.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUComputePassTimestampWrites(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUComputePassTimestampWrites native_new() {
        return new WGPUComputePassTimestampWrites((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUComputePassTimestampWrites* nativeObject = (JGPU::WGPUComputePassTimestampWrites*)this_addr;
delete nativeObject;
*/
    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void setQuerySet(WGPUQuerySet value) {
        internal_native_SetQuerySet(native_address, value.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUComputePassTimestampWrites* nativeObject = (JGPU::WGPUComputePassTimestampWrites*)this_addr;
nativeObject->SetQuerySet((JGPU::WGPUQuerySet* )value_addr);
*/
    public static void internal_native_SetQuerySet(long this_addr, long value_addr) {
        try {
            FFMHandles.internal_native_SetQuerySet__JJ.invokeExact(this_addr, value_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void setBeginningOfPassWriteIndex(int value) {
        internal_native_SetBeginningOfPassWriteIndex(native_address, value);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUComputePassTimestampWrites* nativeObject = (JGPU::WGPUComputePassTimestampWrites*)this_addr;
nativeObject->SetBeginningOfPassWriteIndex((int)value);
*/
    public static void internal_native_SetBeginningOfPassWriteIndex(long this_addr, int value) {
        try {
            FFMHandles.internal_native_SetBeginningOfPassWriteIndex__JI.invokeExact(this_addr, value);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void setEndOfPassWriteIndex(int value) {
        internal_native_SetEndOfPassWriteIndex(native_address, value);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUComputePassTimestampWrites* nativeObject = (JGPU::WGPUComputePassTimestampWrites*)this_addr;
nativeObject->SetEndOfPassWriteIndex((int)value);
*/
    public static void internal_native_SetEndOfPassWriteIndex(long this_addr, int value) {
        try {
            FFMHandles.internal_native_SetEndOfPassWriteIndex__JI.invokeExact(this_addr, value);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public static WGPUComputePassTimestampWrites obtain() {
        long addr = internal_native_Obtain_addr();
        if (addr == 0)
            return WGPUComputePassTimestampWrites.NULL;
        if (WGPUComputePassTimestampWrites_TEMP_STATIC_GEN_0 == null)
            WGPUComputePassTimestampWrites_TEMP_STATIC_GEN_0 = WGPUComputePassTimestampWrites.native_new();
        WGPUComputePassTimestampWrites_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return WGPUComputePassTimestampWrites_TEMP_STATIC_GEN_0;
    }

    /*[-FFM;-NATIVE]
return (int64_t)JGPU::WGPUComputePassTimestampWrites::Obtain();
*/
    public static long internal_native_Obtain_addr() {
        try {
            return (long) FFMHandles.internal_native_Obtain_addr__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP;

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static {
            LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();
        }

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUComputePassTimestampWrites_internal_1native_1deleteNative__J").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetQuerySet__JJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUComputePassTimestampWrites_internal_1native_1SetQuerySet__JJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetBeginningOfPassWriteIndex__JI = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUComputePassTimestampWrites_internal_1native_1SetBeginningOfPassWriteIndex__JI").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_SetEndOfPassWriteIndex__JI = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUComputePassTimestampWrites_internal_1native_1SetEndOfPassWriteIndex__JI").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_Obtain_addr__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUComputePassTimestampWrites_internal_1native_1Obtain_1addr__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_LONG));
    }
}
