/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUFilterMode implements IDLEnum<WGPUFilterMode> {

    CUSTOM(0), Undefined(WGPUFilterMode_Undefined_NATIVE()), Nearest(WGPUFilterMode_Nearest_NATIVE()), Linear(WGPUFilterMode_Linear_NATIVE()), Force32(WGPUFilterMode_Force32_NATIVE());

    private int value;

    private WGPUFilterMode(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUFilterMode setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUFilterMode getCustom() {
        return CUSTOM;
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUFilterMode_Undefined;
*/
    private static int WGPUFilterMode_Undefined_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFilterMode_Undefined_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUFilterMode_Nearest;
*/
    private static int WGPUFilterMode_Nearest_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFilterMode_Nearest_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUFilterMode_Linear;
*/
    private static int WGPUFilterMode_Linear_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFilterMode_Linear_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUFilterMode_Force32;
*/
    private static int WGPUFilterMode_Force32_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFilterMode_Force32_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP;

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static {
            LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();
        }

        static final java.lang.invoke.MethodHandle WGPUFilterMode_Undefined_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUFilterMode_WGPUFilterMode_1Undefined_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFilterMode_Nearest_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUFilterMode_WGPUFilterMode_1Nearest_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFilterMode_Linear_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUFilterMode_WGPUFilterMode_1Linear_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFilterMode_Force32_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUFilterMode_WGPUFilterMode_1Force32_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
