/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUIndexFormat implements IDLEnum<WGPUIndexFormat> {

    CUSTOM(0), Undefined(WGPUIndexFormat_Undefined_NATIVE()), Uint16(WGPUIndexFormat_Uint16_NATIVE()), Uint32(WGPUIndexFormat_Uint32_NATIVE()), Force32(WGPUIndexFormat_Force32_NATIVE());

    private int value;

    private WGPUIndexFormat(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUIndexFormat setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUIndexFormat getCustom() {
        return CUSTOM;
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUIndexFormat_Undefined;
*/
    private static int WGPUIndexFormat_Undefined_NATIVE() {
        try {
            return (int) FFMHandles.WGPUIndexFormat_Undefined_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUIndexFormat_Uint16;
*/
    private static int WGPUIndexFormat_Uint16_NATIVE() {
        try {
            return (int) FFMHandles.WGPUIndexFormat_Uint16_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUIndexFormat_Uint32;
*/
    private static int WGPUIndexFormat_Uint32_NATIVE() {
        try {
            return (int) FFMHandles.WGPUIndexFormat_Uint32_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUIndexFormat_Force32;
*/
    private static int WGPUIndexFormat_Force32_NATIVE() {
        try {
            return (int) FFMHandles.WGPUIndexFormat_Force32_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP;

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static {
            LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();
        }

        static final java.lang.invoke.MethodHandle WGPUIndexFormat_Undefined_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUIndexFormat_WGPUIndexFormat_1Undefined_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUIndexFormat_Uint16_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUIndexFormat_WGPUIndexFormat_1Uint16_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUIndexFormat_Uint32_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUIndexFormat_WGPUIndexFormat_1Uint32_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUIndexFormat_Force32_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUIndexFormat_WGPUIndexFormat_1Force32_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
