/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLEnum;

public enum WGPUInstanceFeatureName implements IDLEnum<WGPUInstanceFeatureName> {

    CUSTOM(0), TimedWaitAny(WGPUInstanceFeatureName_TimedWaitAny_NATIVE()), ShaderSourceSPIRV(WGPUInstanceFeatureName_ShaderSourceSPIRV_NATIVE()), MultipleDevicesPerAdapter(WGPUInstanceFeatureName_MultipleDevicesPerAdapter_NATIVE()), Force32(WGPUInstanceFeatureName_Force32_NATIVE());

    private int value;

    private WGPUInstanceFeatureName(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUInstanceFeatureName setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUInstanceFeatureName getCustom() {
        return CUSTOM;
    }

    /*[-JNI;-NATIVE]
return (jlong)WGPUInstanceFeatureName_TimedWaitAny;
*/
    private static native int WGPUInstanceFeatureName_TimedWaitAny_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUInstanceFeatureName_ShaderSourceSPIRV;
*/
    private static native int WGPUInstanceFeatureName_ShaderSourceSPIRV_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUInstanceFeatureName_MultipleDevicesPerAdapter;
*/
    private static native int WGPUInstanceFeatureName_MultipleDevicesPerAdapter_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUInstanceFeatureName_Force32;
*/
    private static native int WGPUInstanceFeatureName_Force32_NATIVE();
}
