/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu.natives;

import com.github.xpenatan.webgpu.*;

final public class JNI_WGPUByteOrder {

    static native public int BigEndian_NATIVE();

    static native public int LittleEndian_NATIVE();
}
