/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu.natives;

import com.github.xpenatan.webgpu.*;

final public class JNI_WGPUWaitStatus {

    static native public int WGPUWaitStatus_Success_NATIVE();

    static native public int WGPUWaitStatus_TimedOut_NATIVE();

    static native public int WGPUWaitStatus_Force32_NATIVE();
}
