/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu.natives;

import com.github.xpenatan.webgpu.*;

final public class JNI_WGPUByteBuffer {

    public static native long internal_native_create_int_addr(int capacity);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_Obtain_addr(int capacity);

    public static native void internal_native_order(long this_addr, int order);

    public static native byte internal_native_get(long this_addr, int index);

    public static native void internal_native_put__0(long this_addr, byte value);

    public static native void internal_native_put__1(long this_addr, int index, byte value);

    public static native byte internal_native_get(long this_addr);

    public static native void internal_native_putInt(long this_addr, int byteIndex, int value);

    public static native int internal_native_getInt(long this_addr, int byteIndex);

    public static native void internal_native_putFloat(long this_addr, int byteIndex, float value);

    public static native float internal_native_getFloat(long this_addr, int byteIndex);

    public static native int internal_native_remaining(long this_addr);

    public static native int internal_native_getCapacity(long this_addr);

    public static native void internal_native_position(long this_addr, int newPosition);

    public static native int internal_native_getPosition(long this_addr);

    public static native void internal_native_limit(long this_addr, int newLimit);

    public static native int internal_native_getLimit(long this_addr);

    public static native void internal_native_clear(long this_addr);

    public static native void internal_native_flip(long this_addr);

    public static native long internal_native_asFloatBuffer_addr(long this_addr);

    public static native long internal_native_asIntBuffer_addr(long this_addr);

    public static native long internal_native_asLongBuffer_addr(long this_addr);

    public static native long internal_native_asShortBuffer_addr(long this_addr);
}
