/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu.natives;

import com.github.xpenatan.webgpu.*;

final public class JNI_WGPUCommandEncoder {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native void internal_native_SetLabel(long this_addr, String value);

    public static native void internal_native_Release(long this_addr);

    public static native void internal_native_BeginComputePass(long this_addr, long descriptor_addr, long computePassEncoder_addr);

    public static native void internal_native_BeginRenderPass(long this_addr, long renderPassDescriptor_addr, long renderPassEncoder_addr);

    public static native void internal_native_ClearBuffer(long this_addr, long buffer_addr, int offset, int size);

    public static native void internal_native_CopyBufferToBuffer(long this_addr, long source_addr, int sourceOffset, long destination_addr, int destinationOffset, int size);

    public static native void internal_native_CopyBufferToTexture(long this_addr, long source_addr, long destination_addr, long copySize_addr);

    public static native void internal_native_CopyTextureToBuffer(long this_addr, long source_addr, long destination_addr, long copySize_addr);

    public static native void internal_native_CopyTextureToTexture(long this_addr, long source_addr, long destination_addr, long copySize_addr);

    public static native void internal_native_Finish(long this_addr, long descriptor_addr, long commandBuffer_addr);

    public static native void internal_native_InsertDebugMarker(long this_addr, String value);

    public static native void internal_native_PopDebugGroup(long this_addr);

    public static native void internal_native_PushDebugGroup(long this_addr, String value);

    public static native void internal_native_ResolveQuerySet(long this_addr, long querySet_addr, int firstQuery, int queryCount, long destination_addr, int destinationOffset);

    public static native void internal_native_WriteTimestamp(long this_addr, long querySet_addr, int queryIndex);

    public static native boolean internal_native_IsValid(long this_addr);

    public static native long internal_native_Obtain_addr();
}
