/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu.natives;

import com.github.xpenatan.webgpu.*;

final public class JNI_WGPUOptionalBool {

    static native public int WGPUOptionalBool_False_NATIVE();

    static native public int WGPUOptionalBool_True_NATIVE();

    static native public int WGPUOptionalBool_Undefined_NATIVE();

    static native public int WGPUOptionalBool_Force32_NATIVE();
}
