/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu.natives;

import com.github.xpenatan.webgpu.*;

final public class JNI_WGPUStoreOp {

    static native public int WGPUStoreOp_Undefined_NATIVE();

    static native public int WGPUStoreOp_Store_NATIVE();

    static native public int WGPUStoreOp_Discard_NATIVE();

    static native public int WGPUStoreOp_Force32_NATIVE();
}
