/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu.natives;

import com.github.xpenatan.webgpu.*;

final public class JNI_WGPUPrimitiveState {

    public static native void internal_native_deleteNative(long this_addr);

    public static native void internal_native_SetNextInChain(long this_addr, long chainedStruct_addr);

    public static native void internal_native_SetTopology(long this_addr, int value);

    public static native void internal_native_SetStripIndexFormat(long this_addr, int value);

    public static native void internal_native_SetFrontFace(long this_addr, int value);

    public static native void internal_native_SetCullMode(long this_addr, int value);
}
