/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu.natives;

import com.github.xpenatan.webgpu.*;

final public class JNI_WGPUExtent3D {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native void internal_native_SetWidth(long this_addr, int width);

    public static native void internal_native_SetHeight(long this_addr, int height);

    public static native void internal_native_SetDepthOrArrayLayers(long this_addr, int depthOrArrayLayers);

    public static native long internal_native_Obtain_addr();
}
