/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu.natives;

import com.github.xpenatan.webgpu.*;

final public class JNI_WGPUMipmapFilterMode {

    static native public int WGPUMipmapFilterMode_Undefined_NATIVE();

    static native public int WGPUMipmapFilterMode_Nearest_NATIVE();

    static native public int WGPUMipmapFilterMode_Linear_NATIVE();

    static native public int WGPUMipmapFilterMode_Force32_NATIVE();
}
