/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeObject;

public class WGPULimits extends NativeObject {

    static private WGPULimits WGPULimits_TEMP_STATIC_GEN_0;

    static public final WGPULimits NULL = WGPULimits.native_new();

    public WGPULimits() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return n.n498977734.n1301578948();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPULimits(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPULimits native_new() {
        return new WGPULimits((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        n.n498977734.n2443775738(this_addr);
    }

    public void setMaxTextureDimension1D(int value) {
        internal_native_SetMaxTextureDimension1D(native_address, value);
    }

    public static void internal_native_SetMaxTextureDimension1D(long this_addr, int value) {
        n.n498977734.n3722772543(this_addr, value);
    }

    public int getMaxTextureDimension1D() {
        return internal_native_GetMaxTextureDimension1D(native_address);
    }

    public static int internal_native_GetMaxTextureDimension1D(long this_addr) {
        return n.n498977734.n85725168(this_addr);
    }

    public void setMaxTextureDimension2D(int value) {
        internal_native_SetMaxTextureDimension2D(native_address, value);
    }

    public static void internal_native_SetMaxTextureDimension2D(long this_addr, int value) {
        n.n498977734.n1925821184(this_addr, value);
    }

    public int getMaxTextureDimension2D() {
        return internal_native_GetMaxTextureDimension2D(native_address);
    }

    public static int internal_native_GetMaxTextureDimension2D(long this_addr) {
        return n.n498977734.n973228849(this_addr);
    }

    public void setMaxTextureDimension3D(int value) {
        internal_native_SetMaxTextureDimension3D(native_address, value);
    }

    public static void internal_native_SetMaxTextureDimension3D(long this_addr, int value) {
        n.n498977734.n128869825(this_addr, value);
    }

    public int getMaxTextureDimension3D() {
        return internal_native_GetMaxTextureDimension3D(native_address);
    }

    public static int internal_native_GetMaxTextureDimension3D(long this_addr) {
        return n.n498977734.n1860732530(this_addr);
    }

    public void setMaxTextureArrayLayers(int value) {
        internal_native_SetMaxTextureArrayLayers(native_address, value);
    }

    public static void internal_native_SetMaxTextureArrayLayers(long this_addr, int value) {
        n.n498977734.n2609152925(this_addr, value);
    }

    public int getMaxTextureArrayLayers() {
        return internal_native_GetMaxTextureArrayLayers(native_address);
    }

    public static int internal_native_GetMaxTextureArrayLayers(long this_addr) {
        return n.n498977734.n508555854(this_addr);
    }

    public void setMaxBindGroups(int value) {
        internal_native_SetMaxBindGroups(native_address, value);
    }

    public static void internal_native_SetMaxBindGroups(long this_addr, int value) {
        n.n498977734.n4019208492(this_addr, value);
    }

    public int getMaxBindGroups() {
        return internal_native_GetMaxBindGroups(native_address);
    }

    public static int internal_native_GetMaxBindGroups(long this_addr) {
        return n.n498977734.n1188168541(this_addr);
    }

    public void setMaxBindGroupsPlusVertexBuffers(int value) {
        internal_native_SetMaxBindGroupsPlusVertexBuffers(native_address, value);
    }

    public static void internal_native_SetMaxBindGroupsPlusVertexBuffers(long this_addr, int value) {
        n.n498977734.n3377697461(this_addr, value);
    }

    public int getMaxBindGroupsPlusVertexBuffers() {
        return internal_native_GetMaxBindGroupsPlusVertexBuffers(native_address);
    }

    public static int internal_native_GetMaxBindGroupsPlusVertexBuffers(long this_addr) {
        return n.n498977734.n156347390(this_addr);
    }

    public void setMaxBindingsPerBindGroup(int value) {
        internal_native_SetMaxBindingsPerBindGroup(native_address, value);
    }

    public static void internal_native_SetMaxBindingsPerBindGroup(long this_addr, int value) {
        n.n498977734.n857115658(this_addr, value);
    }

    public int getMaxBindingsPerBindGroup() {
        return internal_native_GetMaxBindingsPerBindGroup(native_address);
    }

    public static int internal_native_GetMaxBindingsPerBindGroup(long this_addr) {
        return n.n498977734.n3082718267(this_addr);
    }

    public void setMaxDynamicUniformBuffersPerPipelineLayout(int value) {
        internal_native_SetMaxDynamicUniformBuffersPerPipelineLayout(native_address, value);
    }

    public static void internal_native_SetMaxDynamicUniformBuffersPerPipelineLayout(long this_addr, int value) {
        n.n498977734.n3171651410(this_addr, value);
    }

    public int getMaxDynamicUniformBuffersPerPipelineLayout() {
        return internal_native_GetMaxDynamicUniformBuffersPerPipelineLayout(native_address);
    }

    public static int internal_native_GetMaxDynamicUniformBuffersPerPipelineLayout(long this_addr) {
        return n.n498977734.n1400807043(this_addr);
    }

    public void setMaxDynamicStorageBuffersPerPipelineLayout(int value) {
        internal_native_SetMaxDynamicStorageBuffersPerPipelineLayout(native_address, value);
    }

    public static void internal_native_SetMaxDynamicStorageBuffersPerPipelineLayout(long this_addr, int value) {
        n.n498977734.n1222613867(this_addr, value);
    }

    public int getMaxDynamicStorageBuffersPerPipelineLayout() {
        return internal_native_GetMaxDynamicStorageBuffersPerPipelineLayout(native_address);
    }

    public static int internal_native_GetMaxDynamicStorageBuffersPerPipelineLayout(long this_addr) {
        return n.n498977734.n3404111644(this_addr);
    }

    public void setMaxSampledTexturesPerShaderStage(int value) {
        internal_native_SetMaxSampledTexturesPerShaderStage(native_address, value);
    }

    public static void internal_native_SetMaxSampledTexturesPerShaderStage(long this_addr, int value) {
        n.n498977734.n3461219915(this_addr, value);
    }

    public int getMaxSampledTexturesPerShaderStage() {
        return internal_native_GetMaxSampledTexturesPerShaderStage(native_address);
    }

    public static int internal_native_GetMaxSampledTexturesPerShaderStage(long this_addr) {
        return n.n498977734.n604596116(this_addr);
    }

    public void setMaxSamplersPerShaderStage(int value) {
        internal_native_SetMaxSamplersPerShaderStage(native_address, value);
    }

    public static void internal_native_SetMaxSamplersPerShaderStage(long this_addr, int value) {
        n.n498977734.n1806906454(this_addr, value);
    }

    public int getMaxSamplersPerShaderStage() {
        return internal_native_GetMaxSamplersPerShaderStage(native_address);
    }

    public static int internal_native_GetMaxSamplersPerShaderStage(long this_addr) {
        return n.n498977734.n3338653063(this_addr);
    }

    public void setMaxStorageBuffersPerShaderStage(int value) {
        internal_native_SetMaxStorageBuffersPerShaderStage(native_address, value);
    }

    public static void internal_native_SetMaxStorageBuffersPerShaderStage(long this_addr, int value) {
        n.n498977734.n1604430953(this_addr, value);
    }

    public int getMaxStorageBuffersPerShaderStage() {
        return internal_native_GetMaxStorageBuffersPerShaderStage(native_address);
    }

    public static int internal_native_GetMaxStorageBuffersPerShaderStage(long this_addr) {
        return n.n498977734.n424443930(this_addr);
    }

    public void setMaxStorageTexturesPerShaderStage(int value) {
        internal_native_SetMaxStorageTexturesPerShaderStage(native_address, value);
    }

    public static void internal_native_SetMaxStorageTexturesPerShaderStage(long this_addr, int value) {
        n.n498977734.n3715429290(this_addr, value);
    }

    public int getMaxStorageTexturesPerShaderStage() {
        return internal_native_GetMaxStorageTexturesPerShaderStage(native_address);
    }

    public static int internal_native_GetMaxStorageTexturesPerShaderStage(long this_addr) {
        return n.n498977734.n4047756403(this_addr);
    }

    public void setMaxUniformBuffersPerShaderStage(int value) {
        internal_native_SetMaxUniformBuffersPerShaderStage(native_address, value);
    }

    public static void internal_native_SetMaxUniformBuffersPerShaderStage(long this_addr, int value) {
        n.n498977734.n3926497762(this_addr, value);
    }

    public int getMaxUniformBuffersPerShaderStage() {
        return internal_native_GetMaxUniformBuffersPerShaderStage(native_address);
    }

    public static int internal_native_GetMaxUniformBuffersPerShaderStage(long this_addr) {
        return n.n498977734.n3291484691(this_addr);
    }

    public void setMaxUniformBufferBindingSize(int value) {
        internal_native_SetMaxUniformBufferBindingSize(native_address, value);
    }

    public static void internal_native_SetMaxUniformBufferBindingSize(long this_addr, int value) {
        n.n498977734.n588756683(this_addr, value);
    }

    public int getMaxUniformBufferBindingSize() {
        return internal_native_GetMaxUniformBufferBindingSize(native_address);
    }

    public static int internal_native_GetMaxUniformBufferBindingSize(long this_addr) {
        return n.n498977734.n2709366140(this_addr);
    }

    public void setMaxStorageBufferBindingSize(int value) {
        internal_native_SetMaxStorageBufferBindingSize(native_address, value);
    }

    public static void internal_native_SetMaxStorageBufferBindingSize(long this_addr, int value) {
        n.n498977734.n2016683218(this_addr, value);
    }

    public int getMaxStorageBufferBindingSize() {
        return internal_native_GetMaxStorageBufferBindingSize(native_address);
    }

    public static int internal_native_GetMaxStorageBufferBindingSize(long this_addr) {
        return n.n498977734.n26750723(this_addr);
    }

    public void setMinUniformBufferOffsetAlignment(int value) {
        internal_native_SetMinUniformBufferOffsetAlignment(native_address, value);
    }

    public static void internal_native_SetMinUniformBufferOffsetAlignment(long this_addr, int value) {
        n.n498977734.n1081042035(this_addr, value);
    }

    public int getMinUniformBufferOffsetAlignment() {
        return internal_native_GetMinUniformBufferOffsetAlignment(native_address);
    }

    public static int internal_native_GetMinUniformBufferOffsetAlignment(long this_addr) {
        return n.n498977734.n2885405988(this_addr);
    }

    public void setMinStorageBufferOffsetAlignment(int value) {
        internal_native_SetMinStorageBufferOffsetAlignment(native_address, value);
    }

    public static void internal_native_SetMinStorageBufferOffsetAlignment(long this_addr, int value) {
        n.n498977734.n3053942522(this_addr, value);
    }

    public int getMinStorageBufferOffsetAlignment() {
        return internal_native_GetMinStorageBufferOffsetAlignment(native_address);
    }

    public static int internal_native_GetMinStorageBufferOffsetAlignment(long this_addr) {
        return n.n498977734.n18365227(this_addr);
    }

    public void setMaxVertexBuffers(int value) {
        internal_native_SetMaxVertexBuffers(native_address, value);
    }

    public static void internal_native_SetMaxVertexBuffers(long this_addr, int value) {
        n.n498977734.n90362794(this_addr, value);
    }

    public int getMaxVertexBuffers() {
        return internal_native_GetMaxVertexBuffers(native_address);
    }

    public static int internal_native_GetMaxVertexBuffers(long this_addr) {
        return n.n498977734.n1081496691(this_addr);
    }

    public void setMaxBufferSize(long value) {
        internal_native_SetMaxBufferSize(native_address, value);
    }

    public static void internal_native_SetMaxBufferSize(long this_addr, long value) {
        n.n498977734.n3629832399(this_addr, value);
    }

    public int getMaxBufferSize() {
        return internal_native_GetMaxBufferSize(native_address);
    }

    public static int internal_native_GetMaxBufferSize(long this_addr) {
        return n.n498977734.n3462379885(this_addr);
    }

    public void setMaxVertexAttributes(int value) {
        internal_native_SetMaxVertexAttributes(native_address, value);
    }

    public static void internal_native_SetMaxVertexAttributes(long this_addr, int value) {
        n.n498977734.n3704919362(this_addr, value);
    }

    public int getMaxVertexAttributes() {
        return internal_native_GetMaxVertexAttributes(native_address);
    }

    public static int internal_native_GetMaxVertexAttributes(long this_addr) {
        return n.n498977734.n1136561011(this_addr);
    }

    public void setMaxVertexBufferArrayStride(int value) {
        internal_native_SetMaxVertexBufferArrayStride(native_address, value);
    }

    public static void internal_native_SetMaxVertexBufferArrayStride(long this_addr, int value) {
        n.n498977734.n1421093387(this_addr, value);
    }

    public int getMaxVertexBufferArrayStride() {
        return internal_native_GetMaxVertexBufferArrayStride(native_address);
    }

    public static int internal_native_GetMaxVertexBufferArrayStride(long this_addr) {
        return n.n498977734.n2759951444(this_addr);
    }

    public void setMaxInterStageShaderVariables(int value) {
        internal_native_SetMaxInterStageShaderVariables(native_address, value);
    }

    public static void internal_native_SetMaxInterStageShaderVariables(long this_addr, int value) {
        n.n498977734.n2834773641(this_addr, value);
    }

    public int getMaxInterStageShaderVariables() {
        return internal_native_GetMaxInterStageShaderVariables(native_address);
    }

    public static int internal_native_GetMaxInterStageShaderVariables(long this_addr) {
        return n.n498977734.n4015066322(this_addr);
    }

    public void setMaxColorAttachments(int value) {
        internal_native_SetMaxColorAttachments(native_address, value);
    }

    public static void internal_native_SetMaxColorAttachments(long this_addr, int value) {
        n.n498977734.n705302352(this_addr, value);
    }

    public int getMaxColorAttachments() {
        return internal_native_GetMaxColorAttachments(native_address);
    }

    public static int internal_native_GetMaxColorAttachments(long this_addr) {
        return n.n498977734.n1777286273(this_addr);
    }

    public void setMaxColorAttachmentBytesPerSample(int value) {
        internal_native_SetMaxColorAttachmentBytesPerSample(native_address, value);
    }

    public static void internal_native_SetMaxColorAttachmentBytesPerSample(long this_addr, int value) {
        n.n498977734.n2410835831(this_addr, value);
    }

    public int getMaxColorAttachmentBytesPerSample() {
        return internal_native_GetMaxColorAttachmentBytesPerSample(native_address);
    }

    public static int internal_native_GetMaxColorAttachmentBytesPerSample(long this_addr) {
        return n.n498977734.n3020506816(this_addr);
    }

    public void setMaxComputeWorkgroupStorageSize(int value) {
        internal_native_SetMaxComputeWorkgroupStorageSize(native_address, value);
    }

    public static void internal_native_SetMaxComputeWorkgroupStorageSize(long this_addr, int value) {
        n.n498977734.n921736404(this_addr, value);
    }

    public int getMaxComputeWorkgroupStorageSize() {
        return internal_native_GetMaxComputeWorkgroupStorageSize(native_address);
    }

    public static int internal_native_GetMaxComputeWorkgroupStorageSize(long this_addr) {
        return n.n498977734.n382375325(this_addr);
    }

    public void setMaxComputeInvocationsPerWorkgroup(int value) {
        internal_native_SetMaxComputeInvocationsPerWorkgroup(native_address, value);
    }

    public static void internal_native_SetMaxComputeInvocationsPerWorkgroup(long this_addr, int value) {
        n.n498977734.n2257167712(this_addr, value);
    }

    public int getMaxComputeInvocationsPerWorkgroup() {
        return internal_native_GetMaxComputeInvocationsPerWorkgroup(native_address);
    }

    public static int internal_native_GetMaxComputeInvocationsPerWorkgroup(long this_addr) {
        return n.n498977734.n764878737(this_addr);
    }

    public void setMaxComputeWorkgroupSizeX(int value) {
        internal_native_SetMaxComputeWorkgroupSizeX(native_address, value);
    }

    public static void internal_native_SetMaxComputeWorkgroupSizeX(long this_addr, int value) {
        n.n498977734.n2985211801(this_addr, value);
    }

    public int getMaxComputeWorkgroupSizeX() {
        return internal_native_GetMaxComputeWorkgroupSizeX(native_address);
    }

    public static int internal_native_GetMaxComputeWorkgroupSizeX(long this_addr) {
        return n.n498977734.n2391227362(this_addr);
    }

    public void setMaxComputeWorkgroupSizeY(int value) {
        internal_native_SetMaxComputeWorkgroupSizeY(native_address, value);
    }

    public static void internal_native_SetMaxComputeWorkgroupSizeY(long this_addr, int value) {
        n.n498977734.n2788698296(this_addr, value);
    }

    public int getMaxComputeWorkgroupSizeY() {
        return internal_native_GetMaxComputeWorkgroupSizeY(native_address);
    }

    public static int internal_native_GetMaxComputeWorkgroupSizeY(long this_addr) {
        return n.n498977734.n2419856513(this_addr);
    }

    public void setMaxComputeWorkgroupSizeZ(int value) {
        internal_native_SetMaxComputeWorkgroupSizeZ(native_address, value);
    }

    public static void internal_native_SetMaxComputeWorkgroupSizeZ(long this_addr, int value) {
        n.n498977734.n2592184791(this_addr, value);
    }

    public int getMaxComputeWorkgroupSizeZ() {
        return internal_native_GetMaxComputeWorkgroupSizeZ(native_address);
    }

    public static int internal_native_GetMaxComputeWorkgroupSizeZ(long this_addr) {
        return n.n498977734.n2448485664(this_addr);
    }

    public void setMaxComputeWorkgroupsPerDimension(int value) {
        internal_native_SetMaxComputeWorkgroupsPerDimension(native_address, value);
    }

    public static void internal_native_SetMaxComputeWorkgroupsPerDimension(long this_addr, int value) {
        n.n498977734.n563444660(this_addr, value);
    }

    public int getMaxComputeWorkgroupsPerDimension() {
        return internal_native_GetMaxComputeWorkgroupsPerDimension(native_address);
    }

    public static int internal_native_GetMaxComputeWorkgroupsPerDimension(long this_addr) {
        return n.n498977734.n2704144765(this_addr);
    }

    public static WGPULimits obtain() {
        long addr = internal_native_Obtain_addr();
        if (addr == 0)
            return WGPULimits.NULL;
        if (WGPULimits_TEMP_STATIC_GEN_0 == null)
            WGPULimits_TEMP_STATIC_GEN_0 = WGPULimits.native_new();
        WGPULimits_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return WGPULimits_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_Obtain_addr() {
        return n.n498977734.n455161293();
    }
}
