/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeObject;

public class WGPUQuerySetDescriptor extends NativeObject {

    static private WGPUQuerySetDescriptor WGPUQuerySetDescriptor_TEMP_STATIC_GEN_0;

    static public final WGPUQuerySetDescriptor NULL = WGPUQuerySetDescriptor.native_new();

    public WGPUQuerySetDescriptor() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUQuerySetDescriptor.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUQuerySetDescriptor(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUQuerySetDescriptor native_new() {
        return new WGPUQuerySetDescriptor((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUQuerySetDescriptor.internal_native_deleteNative(this_addr);
    }

    public void setLabel(String label) {
        internal_native_SetLabel(native_address, label);
    }

    public static void internal_native_SetLabel(long this_addr, String label) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUQuerySetDescriptor.internal_native_SetLabel(this_addr, label);
    }

    public void setNextInChain(WGPUChainedStruct chainedStruct) {
        internal_native_SetNextInChain(native_address, chainedStruct.native_address);
    }

    public static void internal_native_SetNextInChain(long this_addr, long chainedStruct_addr) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUQuerySetDescriptor.internal_native_SetNextInChain(this_addr, chainedStruct_addr);
    }

    public void setType(WGPUQueryType type) {
        internal_native_SetType(native_address, type.getValue());
    }

    public static void internal_native_SetType(long this_addr, int type) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUQuerySetDescriptor.internal_native_SetType(this_addr, type);
    }

    public void setCount(int count) {
        internal_native_SetCount(native_address, count);
    }

    public static void internal_native_SetCount(long this_addr, int count) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUQuerySetDescriptor.internal_native_SetCount(this_addr, count);
    }

    public static WGPUQuerySetDescriptor obtain() {
        long addr = internal_native_Obtain_addr();
        if (addr == 0)
            return WGPUQuerySetDescriptor.NULL;
        if (WGPUQuerySetDescriptor_TEMP_STATIC_GEN_0 == null)
            WGPUQuerySetDescriptor_TEMP_STATIC_GEN_0 = WGPUQuerySetDescriptor.native_new();
        WGPUQuerySetDescriptor_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return WGPUQuerySetDescriptor_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_Obtain_addr() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUQuerySetDescriptor.internal_native_Obtain_addr();
    }
}
