/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum WGPUFeatureLevel implements NativeEnum<WGPUFeatureLevel> {

    CUSTOM(0), Compatibility(WGPUFeatureLevel_Compatibility_NATIVE()), Core(WGPUFeatureLevel_Core_NATIVE()), Force32(WGPUFeatureLevel_Force32_NATIVE());

    private int value;

    private WGPUFeatureLevel(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUFeatureLevel setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUFeatureLevel getCustom() {
        return CUSTOM;
    }

    private static int WGPUFeatureLevel_Compatibility_NATIVE() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUFeatureLevel.WGPUFeatureLevel_Compatibility_NATIVE();
    }

    private static int WGPUFeatureLevel_Core_NATIVE() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUFeatureLevel.WGPUFeatureLevel_Core_NATIVE();
    }

    private static int WGPUFeatureLevel_Force32_NATIVE() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUFeatureLevel.WGPUFeatureLevel_Force32_NATIVE();
    }
}
