/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeObject;

public class WGPUVectorRenderBundle extends NativeObject {

    static private WGPUVectorRenderBundle WGPUVectorRenderBundle_TEMP_STATIC_GEN_0;

    static public final WGPUVectorRenderBundle NULL = WGPUVectorRenderBundle.native_new();

    public WGPUVectorRenderBundle() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUVectorRenderBundle.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUVectorRenderBundle(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUVectorRenderBundle native_new() {
        return new WGPUVectorRenderBundle((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUVectorRenderBundle.internal_native_deleteNative(this_addr);
    }

    public int size() {
        return internal_native_size(native_address);
    }

    public static int internal_native_size(long this_addr) {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUVectorRenderBundle.internal_native_size(this_addr);
    }

    public void clear() {
        internal_native_clear(native_address);
    }

    public static void internal_native_clear(long this_addr) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUVectorRenderBundle.internal_native_clear(this_addr);
    }

    public void push_back(WGPURenderBundle renderBundle) {
        internal_native_push_back(native_address, renderBundle.native_address);
    }

    public static void internal_native_push_back(long this_addr, long renderBundle_addr) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUVectorRenderBundle.internal_native_push_back(this_addr, renderBundle_addr);
    }

    public static WGPUVectorRenderBundle obtain() {
        long addr = internal_native_Obtain_addr();
        if (addr == 0)
            return WGPUVectorRenderBundle.NULL;
        if (WGPUVectorRenderBundle_TEMP_STATIC_GEN_0 == null)
            WGPUVectorRenderBundle_TEMP_STATIC_GEN_0 = WGPUVectorRenderBundle.native_new();
        WGPUVectorRenderBundle_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return WGPUVectorRenderBundle_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_Obtain_addr() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUVectorRenderBundle.internal_native_Obtain_addr();
    }
}
