/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum WGPUBackendType implements NativeEnum<WGPUBackendType> {

    CUSTOM(0),
    Undefined(WGPUBackendType_Undefined_NATIVE()),
    Null(WGPUBackendType_Null_NATIVE()),
    WebGPU(WGPUBackendType_WebGPU_NATIVE()),
    D3D11(WGPUBackendType_D3D11_NATIVE()),
    D3D12(WGPUBackendType_D3D12_NATIVE()),
    Metal(WGPUBackendType_Metal_NATIVE()),
    Vulkan(WGPUBackendType_Vulkan_NATIVE()),
    OpenGL(WGPUBackendType_OpenGL_NATIVE()),
    OpenGLES(WGPUBackendType_OpenGLES_NATIVE()),
    Force32(WGPUBackendType_Force32_NATIVE());

    private int value;

    private WGPUBackendType(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUBackendType setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUBackendType getCustom() {
        return CUSTOM;
    }

    private static int WGPUBackendType_Undefined_NATIVE() {
        return n.n528981248.n2561529940();
    }

    private static int WGPUBackendType_Null_NATIVE() {
        return n.n528981248.n3956878543();
    }

    private static int WGPUBackendType_WebGPU_NATIVE() {
        return n.n528981248.n799815296();
    }

    private static int WGPUBackendType_D3D11_NATIVE() {
        return n.n528981248.n2201670585();
    }

    private static int WGPUBackendType_D3D12_NATIVE() {
        return n.n528981248.n394216122();
    }

    private static int WGPUBackendType_Metal_NATIVE() {
        return n.n528981248.n1257548299();
    }

    private static int WGPUBackendType_Vulkan_NATIVE() {
        return n.n528981248.n648529907();
    }

    private static int WGPUBackendType_OpenGL_NATIVE() {
        return n.n528981248.n1498315639();
    }

    private static int WGPUBackendType_OpenGLES_NATIVE() {
        return n.n528981248.n918183397();
    }

    private static int WGPUBackendType_Force32_NATIVE() {
        return n.n528981248.n2337883918();
    }
}
