/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum WGPUShaderStage implements NativeEnum<WGPUShaderStage> {

    CUSTOM(0), None(WGPUShaderStage_None_NATIVE()), Vertex(WGPUShaderStage_Vertex_NATIVE()), Fragment(WGPUShaderStage_Fragment_NATIVE()), Compute(WGPUShaderStage_Compute_NATIVE());

    private int value;

    private WGPUShaderStage(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUShaderStage setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUShaderStage getCustom() {
        return CUSTOM;
    }

    private static int WGPUShaderStage_None_NATIVE() {
        return n.n3069869867.n1502561002();
    }

    private static int WGPUShaderStage_Vertex_NATIVE() {
        return n.n3069869867.n3069599318();
    }

    private static int WGPUShaderStage_Fragment_NATIVE() {
        return n.n3069869867.n2445486082();
    }

    private static int WGPUShaderStage_Compute_NATIVE() {
        return n.n3069869867.n4100911633();
    }
}
