/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum WGPUErrorFilter implements NativeEnum<WGPUErrorFilter> {

    CUSTOM(0), Validation(WGPUErrorFilter_Validation_NATIVE()), OutOfMemory(WGPUErrorFilter_OutOfMemory_NATIVE()), Internal(WGPUErrorFilter_Internal_NATIVE()), Force32(WGPUErrorFilter_Force32_NATIVE());

    private int value;

    private WGPUErrorFilter(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUErrorFilter setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUErrorFilter getCustom() {
        return CUSTOM;
    }

    private static int WGPUErrorFilter_Validation_NATIVE() {
        return n.n3529367730.n3288915549();
    }

    private static int WGPUErrorFilter_OutOfMemory_NATIVE() {
        return n.n3529367730.n2662457870();
    }

    private static int WGPUErrorFilter_Internal_NATIVE() {
        return n.n3529367730.n382040097();
    }

    private static int WGPUErrorFilter_Force32_NATIVE() {
        return n.n3529367730.n779149938();
    }
}
