/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum WGPUAddressMode implements NativeEnum<WGPUAddressMode> {

    CUSTOM(0),
    Undefined(WGPUAddressMode_Undefined_NATIVE()),
    ClampToEdge(WGPUAddressMode_ClampToEdge_NATIVE()),
    Repeat(WGPUAddressMode_Repeat_NATIVE()),
    MirrorRepeat(WGPUAddressMode_MirrorRepeat_NATIVE()),
    Force32(WGPUAddressMode_Force32_NATIVE());

    private int value;

    private WGPUAddressMode(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUAddressMode setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUAddressMode getCustom() {
        return CUSTOM;
    }

    private static int WGPUAddressMode_Undefined_NATIVE() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUAddressMode.WGPUAddressMode_Undefined_NATIVE();
    }

    private static int WGPUAddressMode_ClampToEdge_NATIVE() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUAddressMode.WGPUAddressMode_ClampToEdge_NATIVE();
    }

    private static int WGPUAddressMode_Repeat_NATIVE() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUAddressMode.WGPUAddressMode_Repeat_NATIVE();
    }

    private static int WGPUAddressMode_MirrorRepeat_NATIVE() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUAddressMode.WGPUAddressMode_MirrorRepeat_NATIVE();
    }

    private static int WGPUAddressMode_Force32_NATIVE() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUAddressMode.WGPUAddressMode_Force32_NATIVE();
    }
}
