/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeObject;

public class WGPUBufferDescriptor extends NativeObject {

    static private WGPUBufferDescriptor WGPUBufferDescriptor_TEMP_STATIC_GEN_0;

    static public final WGPUBufferDescriptor NULL = WGPUBufferDescriptor.native_new();

    public WGPUBufferDescriptor() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return n.n134500861.n402431469();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUBufferDescriptor(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUBufferDescriptor native_new() {
        return new WGPUBufferDescriptor((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        n.n134500861.n4150216561(this_addr);
    }

    public void setLabel(String label) {
        internal_native_SetLabel(native_address, label);
    }

    public static void internal_native_SetLabel(long this_addr, String label) {
        n.n134500861.n810128252(this_addr, label);
    }

    public void setNextInChain(WGPUChainedStruct chainedStruct) {
        internal_native_SetNextInChain(native_address, chainedStruct.native_address);
    }

    public static void internal_native_SetNextInChain(long this_addr, long chainedStruct_addr) {
        n.n134500861.n2446073660(this_addr, chainedStruct_addr);
    }

    public void setUsage(WGPUBufferUsage usage) {
        internal_native_SetUsage(native_address, usage.getValue());
    }

    public static void internal_native_SetUsage(long this_addr, int usage) {
        n.n134500861.n282706039(this_addr, usage);
    }

    public void setSize(long size) {
        internal_native_SetSize(native_address, size);
    }

    public static void internal_native_SetSize(long this_addr, long size) {
        n.n134500861.n881527086(this_addr, size);
    }

    public void setMappedAtCreation(boolean mappedAtCreation) {
        internal_native_SetMappedAtCreation(native_address, mappedAtCreation);
    }

    public static void internal_native_SetMappedAtCreation(long this_addr, boolean mappedAtCreation) {
        n.n134500861.n2257847154(this_addr, mappedAtCreation);
    }

    public static WGPUBufferDescriptor obtain() {
        long addr = internal_native_Obtain_addr();
        if (addr == 0)
            return WGPUBufferDescriptor.NULL;
        if (WGPUBufferDescriptor_TEMP_STATIC_GEN_0 == null)
            WGPUBufferDescriptor_TEMP_STATIC_GEN_0 = WGPUBufferDescriptor.native_new();
        WGPUBufferDescriptor_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return WGPUBufferDescriptor_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_Obtain_addr() {
        return n.n134500861.n3850981110();
    }
}
