/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum WGPUBufferMapState implements NativeEnum<WGPUBufferMapState> {

    CUSTOM(0), Unmapped(WGPUBufferMapState_Unmapped_NATIVE()), Pending(WGPUBufferMapState_Pending_NATIVE()), Mapped(WGPUBufferMapState_Mapped_NATIVE()), Force32(WGPUBufferMapState_Force32_NATIVE());

    private int value;

    private WGPUBufferMapState(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUBufferMapState setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUBufferMapState getCustom() {
        return CUSTOM;
    }

    private static int WGPUBufferMapState_Unmapped_NATIVE() {
        return n.n2448224931.n4115752398();
    }

    private static int WGPUBufferMapState_Pending_NATIVE() {
        return n.n2448224931.n3498290017();
    }

    private static int WGPUBufferMapState_Mapped_NATIVE() {
        return n.n2448224931.n3116471797();
    }

    private static int WGPUBufferMapState_Force32_NATIVE() {
        return n.n2448224931.n2152399188();
    }
}
