/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeObject;

public class WGPUSamplerDescriptor extends NativeObject {

    static private WGPUSamplerDescriptor WGPUSamplerDescriptor_TEMP_STATIC_GEN_0;

    static public final WGPUSamplerDescriptor NULL = WGPUSamplerDescriptor.native_new();

    public WGPUSamplerDescriptor() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUSamplerDescriptor.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUSamplerDescriptor(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUSamplerDescriptor native_new() {
        return new WGPUSamplerDescriptor((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUSamplerDescriptor.internal_native_deleteNative(this_addr);
    }

    public void setLabel(String label) {
        internal_native_SetLabel(native_address, label);
    }

    public static void internal_native_SetLabel(long this_addr, String label) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUSamplerDescriptor.internal_native_SetLabel(this_addr, label);
    }

    public void setNextInChain(WGPUChainedStruct chainedStruct) {
        internal_native_SetNextInChain(native_address, chainedStruct.native_address);
    }

    public static void internal_native_SetNextInChain(long this_addr, long chainedStruct_addr) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUSamplerDescriptor.internal_native_SetNextInChain(this_addr, chainedStruct_addr);
    }

    public void setAddressModeU(WGPUAddressMode addressModeU) {
        internal_native_SetAddressModeU(native_address, addressModeU.getValue());
    }

    public static void internal_native_SetAddressModeU(long this_addr, int addressModeU) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUSamplerDescriptor.internal_native_SetAddressModeU(this_addr, addressModeU);
    }

    public void setAddressModeV(WGPUAddressMode addressModeV) {
        internal_native_SetAddressModeV(native_address, addressModeV.getValue());
    }

    public static void internal_native_SetAddressModeV(long this_addr, int addressModeV) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUSamplerDescriptor.internal_native_SetAddressModeV(this_addr, addressModeV);
    }

    public void setAddressModeW(WGPUAddressMode addressModeW) {
        internal_native_SetAddressModeW(native_address, addressModeW.getValue());
    }

    public static void internal_native_SetAddressModeW(long this_addr, int addressModeW) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUSamplerDescriptor.internal_native_SetAddressModeW(this_addr, addressModeW);
    }

    public void setMagFilter(WGPUFilterMode magFilter) {
        internal_native_SetMagFilter(native_address, magFilter.getValue());
    }

    public static void internal_native_SetMagFilter(long this_addr, int magFilter) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUSamplerDescriptor.internal_native_SetMagFilter(this_addr, magFilter);
    }

    public void setMinFilter(WGPUFilterMode minFilter) {
        internal_native_SetMinFilter(native_address, minFilter.getValue());
    }

    public static void internal_native_SetMinFilter(long this_addr, int minFilter) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUSamplerDescriptor.internal_native_SetMinFilter(this_addr, minFilter);
    }

    public void setMipmapFilter(WGPUMipmapFilterMode mipmapFilter) {
        internal_native_SetMipmapFilter(native_address, mipmapFilter.getValue());
    }

    public static void internal_native_SetMipmapFilter(long this_addr, int mipmapFilter) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUSamplerDescriptor.internal_native_SetMipmapFilter(this_addr, mipmapFilter);
    }

    public void setLodMinClamp(float lodMinClamp) {
        internal_native_SetLodMinClamp(native_address, lodMinClamp);
    }

    public static void internal_native_SetLodMinClamp(long this_addr, float lodMinClamp) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUSamplerDescriptor.internal_native_SetLodMinClamp(this_addr, lodMinClamp);
    }

    public void setLodMaxClamp(float lodMaxClamp) {
        internal_native_SetLodMaxClamp(native_address, lodMaxClamp);
    }

    public static void internal_native_SetLodMaxClamp(long this_addr, float lodMaxClamp) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUSamplerDescriptor.internal_native_SetLodMaxClamp(this_addr, lodMaxClamp);
    }

    public void setCompare(WGPUCompareFunction compare) {
        internal_native_SetCompare(native_address, compare.getValue());
    }

    public static void internal_native_SetCompare(long this_addr, int compare) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUSamplerDescriptor.internal_native_SetCompare(this_addr, compare);
    }

    public void setMaxAnisotropy(int maxAnisotropy) {
        internal_native_SetMaxAnisotropy(native_address, maxAnisotropy);
    }

    public static void internal_native_SetMaxAnisotropy(long this_addr, int maxAnisotropy) {
        com.github.xpenatan.webgpu.natives.JNI_WGPUSamplerDescriptor.internal_native_SetMaxAnisotropy(this_addr, maxAnisotropy);
    }

    public static WGPUSamplerDescriptor obtain() {
        long addr = internal_native_Obtain_addr();
        if (addr == 0)
            return WGPUSamplerDescriptor.NULL;
        if (WGPUSamplerDescriptor_TEMP_STATIC_GEN_0 == null)
            WGPUSamplerDescriptor_TEMP_STATIC_GEN_0 = WGPUSamplerDescriptor.native_new();
        WGPUSamplerDescriptor_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return WGPUSamplerDescriptor_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_Obtain_addr() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUSamplerDescriptor.internal_native_Obtain_addr();
    }
}
