/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum WGPUPlatformType implements NativeEnum<WGPUPlatformType> {

    CUSTOM(0),
    WGPU_Windows(WGPU_Windows_NATIVE()),
    WGPU_Mac(WGPU_Mac_NATIVE()),
    WGPU_Linux(WGPU_Linux_NATIVE()),
    WGPU_iOS(WGPU_iOS_NATIVE()),
    WGPU_Android(WGPU_Android_NATIVE()),
    WGPU_Web(WGPU_Web_NATIVE()),
    WGPU_Unknown(WGPU_Unknown_NATIVE());

    private int value;

    private WGPUPlatformType(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUPlatformType setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUPlatformType getCustom() {
        return CUSTOM;
    }

    private static int WGPU_Windows_NATIVE() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUPlatformType.WGPU_Windows_NATIVE();
    }

    private static int WGPU_Mac_NATIVE() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUPlatformType.WGPU_Mac_NATIVE();
    }

    private static int WGPU_Linux_NATIVE() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUPlatformType.WGPU_Linux_NATIVE();
    }

    private static int WGPU_iOS_NATIVE() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUPlatformType.WGPU_iOS_NATIVE();
    }

    private static int WGPU_Android_NATIVE() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUPlatformType.WGPU_Android_NATIVE();
    }

    private static int WGPU_Web_NATIVE() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUPlatformType.WGPU_Web_NATIVE();
    }

    private static int WGPU_Unknown_NATIVE() {
        return com.github.xpenatan.webgpu.natives.JNI_WGPUPlatformType.WGPU_Unknown_NATIVE();
    }
}
