/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class WGPUCompilationInfo extends NativeObject {

    private WGPUCompilationMessage WGPUCompilationMessage_TEMP_GEN_0;

    static public final WGPUCompilationInfo NULL = WGPUCompilationInfo.native_new();

    public WGPUCompilationInfo() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUCompilationInfo(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUCompilationInfo native_new() {
        return new WGPUCompilationInfo((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int getMessageCount() {
        return internal_native_GetMessageCount(native_address);
    }

    public static int internal_native_GetMessageCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetMessageCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public WGPUCompilationMessage getMessage(int index) {
        long addr = internal_native_GetMessage_addr(native_address, index);
        if (addr == 0)
            return WGPUCompilationMessage.NULL;
        if (WGPUCompilationMessage_TEMP_GEN_0 == null)
            WGPUCompilationMessage_TEMP_GEN_0 = WGPUCompilationMessage.native_new();
        WGPUCompilationMessage_TEMP_GEN_0.internal_reset(addr, false);
        return WGPUCompilationMessage_TEMP_GEN_0;
    }

    public static long internal_native_GetMessage_addr(long this_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_GetMessage_addr__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3228264583", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n493423895", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetMessageCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n924943353", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetMessage_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1866223867", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));
    }
}
