/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUBlendOperation implements NativeEnum<WGPUBlendOperation> {

    CUSTOM(0),
    Undefined(WGPUBlendOperation_Undefined_NATIVE()),
    Add(WGPUBlendOperation_Add_NATIVE()),
    Subtract(WGPUBlendOperation_Subtract_NATIVE()),
    ReverseSubtract(WGPUBlendOperation_ReverseSubtract_NATIVE()),
    Min(WGPUBlendOperation_Min_NATIVE()),
    Max(WGPUBlendOperation_Max_NATIVE()),
    Force32(WGPUBlendOperation_Force32_NATIVE());

    private int value;

    private WGPUBlendOperation(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUBlendOperation setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUBlendOperation getCustom() {
        return CUSTOM;
    }

    private static int WGPUBlendOperation_Undefined_NATIVE() {
        try {
            return (int) FFMHandles.WGPUBlendOperation_Undefined_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUBlendOperation_Add_NATIVE() {
        try {
            return (int) FFMHandles.WGPUBlendOperation_Add_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUBlendOperation_Subtract_NATIVE() {
        try {
            return (int) FFMHandles.WGPUBlendOperation_Subtract_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUBlendOperation_ReverseSubtract_NATIVE() {
        try {
            return (int) FFMHandles.WGPUBlendOperation_ReverseSubtract_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUBlendOperation_Min_NATIVE() {
        try {
            return (int) FFMHandles.WGPUBlendOperation_Min_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUBlendOperation_Max_NATIVE() {
        try {
            return (int) FFMHandles.WGPUBlendOperation_Max_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUBlendOperation_Force32_NATIVE() {
        try {
            return (int) FFMHandles.WGPUBlendOperation_Force32_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle WGPUBlendOperation_Undefined_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpublendoperation_wgpublendoperation_undefined_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBlendOperation_Add_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpublendoperation_wgpublendoperation_add_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBlendOperation_Subtract_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpublendoperation_wgpublendoperation_subtract_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBlendOperation_ReverseSubtract_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpublendoperation_wgpublendoperation_reversesubtract_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBlendOperation_Min_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpublendoperation_wgpublendoperation_min_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBlendOperation_Max_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpublendoperation_wgpublendoperation_max_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBlendOperation_Force32_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpublendoperation_wgpublendoperation_force32_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
