/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;
import com.github.xpenatan.jparser.idl.helper.IDLString;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class WGPUStringView extends IDLBase {

    private IDLString IDLString_TEMP_GEN_0;

    static public final WGPUStringView NULL = WGPUStringView.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUStringView(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUStringView native_new() {
        return new WGPUStringView((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUStringView* nativeObject = (JGPU::WGPUStringView*)this_addr;
delete nativeObject;
*/
    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public IDLString getString() {
        long addr = internal_native_GetString_addr(native_address);
        if (addr == 0)
            return IDLString.NULL;
        if (IDLString_TEMP_GEN_0 == null)
            IDLString_TEMP_GEN_0 = IDLString.native_new();
        IDLString_TEMP_GEN_0.internal_reset(addr, false);
        return IDLString_TEMP_GEN_0;
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUStringView* nativeObject = (JGPU::WGPUStringView*)this_addr;
static IDLString copy_addr;
copy_addr = nativeObject->GetString();
return (int64_t)&copy_addr;*/
    public static long internal_native_GetString_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetString_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP;

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static {
            LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();
        }

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUStringView_internal_1native_1deleteNative__J").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetString_addr__J = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUStringView_internal_1native_1GetString_1addr__J").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
