/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class WGPUShaderSourceSPIRV extends NativeObject {

    static private WGPUShaderSourceSPIRV WGPUShaderSourceSPIRV_TEMP_STATIC_GEN_0;

    static public final WGPUShaderSourceSPIRV NULL = WGPUShaderSourceSPIRV.native_new();

    public WGPUShaderSourceSPIRV() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUShaderSourceSPIRV(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUShaderSourceSPIRV native_new() {
        return new WGPUShaderSourceSPIRV((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static WGPUShaderSourceSPIRV obtain() {
        long addr = internal_native_Obtain_addr();
        if (addr == 0)
            return WGPUShaderSourceSPIRV.NULL;
        if (WGPUShaderSourceSPIRV_TEMP_STATIC_GEN_0 == null)
            WGPUShaderSourceSPIRV_TEMP_STATIC_GEN_0 = WGPUShaderSourceSPIRV.native_new();
        WGPUShaderSourceSPIRV_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return WGPUShaderSourceSPIRV_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_Obtain_addr() {
        try {
            return (long) FFMHandles.internal_native_Obtain_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3063896584", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n723838006", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Obtain_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2217478929", FunctionDescriptor.of(ValueLayout.JAVA_LONG));
    }
}
