/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class WGPUSurfaceCapabilities extends NativeObject {

    private WGPUVectorTextureFormat WGPUVectorTextureFormat_TEMP_GEN_0;

    static private WGPUSurfaceCapabilities WGPUSurfaceCapabilities_TEMP_STATIC_GEN_0;

    static public final WGPUSurfaceCapabilities NULL = WGPUSurfaceCapabilities.native_new();

    public WGPUSurfaceCapabilities() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3088205525", "WGPUSurfaceCapabilities.internal_native_create_addr");
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUSurfaceCapabilities(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUSurfaceCapabilities native_new() {
        return new WGPUSurfaceCapabilities((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1450635145", "WGPUSurfaceCapabilities.internal_native_deleteNative");
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public WGPUVectorTextureFormat getFormats() {
        long addr = internal_native_GetFormats_addr(native_address);
        if (addr == 0)
            return WGPUVectorTextureFormat.NULL;
        if (WGPUVectorTextureFormat_TEMP_GEN_0 == null)
            WGPUVectorTextureFormat_TEMP_GEN_0 = WGPUVectorTextureFormat.native_new();
        WGPUVectorTextureFormat_TEMP_GEN_0.internal_reset(addr, false);
        return WGPUVectorTextureFormat_TEMP_GEN_0;
    }

    public static long internal_native_GetFormats_addr(long this_addr) {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3461948955", "WGPUSurfaceCapabilities.internal_native_GetFormats_addr");
            return (long) FFMHandles.internal_native_GetFormats_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static WGPUSurfaceCapabilities obtain() {
        long addr = internal_native_Obtain_addr();
        if (addr == 0)
            return WGPUSurfaceCapabilities.NULL;
        if (WGPUSurfaceCapabilities_TEMP_STATIC_GEN_0 == null)
            WGPUSurfaceCapabilities_TEMP_STATIC_GEN_0 = WGPUSurfaceCapabilities.native_new();
        WGPUSurfaceCapabilities_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return WGPUSurfaceCapabilities_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_Obtain_addr() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2241787870", "WGPUSurfaceCapabilities.internal_native_Obtain_addr");
            return (long) FFMHandles.internal_native_Obtain_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3088205525", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1450635145", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetFormats_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3461948955", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Obtain_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2241787870", FunctionDescriptor.of(ValueLayout.JAVA_LONG));
    }
}
