/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUFrontFace implements NativeEnum<WGPUFrontFace> {

    CUSTOM(0), Undefined(WGPUFrontFace_Undefined_NATIVE()), CCW(WGPUFrontFace_CCW_NATIVE()), CW(WGPUFrontFace_CW_NATIVE()), Force32(WGPUFrontFace_Force32_NATIVE());

    private int value;

    private WGPUFrontFace(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUFrontFace setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUFrontFace getCustom() {
        return CUSTOM;
    }

    private static int WGPUFrontFace_Undefined_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFrontFace_Undefined_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFrontFace_CCW_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFrontFace_CCW_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFrontFace_CW_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFrontFace_CW_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFrontFace_Force32_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFrontFace_Force32_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle WGPUFrontFace_Undefined_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpufrontface_wgpufrontface_undefined_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFrontFace_CCW_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpufrontface_wgpufrontface_ccw_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFrontFace_CW_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpufrontface_wgpufrontface_cw_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFrontFace_Force32_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpufrontface_wgpufrontface_force32_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
