/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class WGPUColor extends NativeObject {

    static private WGPUColor WGPUColor_TEMP_STATIC_GEN_0;

    static public final WGPUColor NULL = WGPUColor.native_new();

    public WGPUColor() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    /*[-FFM;-NATIVE]
return (int64_t)new JGPU::WGPUColor();
*/
    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUColor(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUColor native_new() {
        return new WGPUColor((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUColor* nativeObject = (JGPU::WGPUColor*)this_addr;
delete nativeObject;
*/
    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void setColor(float r, float g, float b, float a) {
        internal_native_SetColor(native_address, r, g, b, a);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUColor* nativeObject = (JGPU::WGPUColor*)this_addr;
nativeObject->SetColor((float)r, (float)g, (float)b, (float)a);
*/
    public static void internal_native_SetColor(long this_addr, float r, float g, float b, float a) {
        try {
            FFMHandles.internal_native_SetColor__JFFFF.invokeExact(this_addr, r, g, b, a);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void setR(float value) {
        internal_native_SetR(native_address, value);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUColor* nativeObject = (JGPU::WGPUColor*)this_addr;
nativeObject->SetR((float)value);
*/
    public static void internal_native_SetR(long this_addr, float value) {
        try {
            FFMHandles.internal_native_SetR__JF.invokeExact(this_addr, value);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void setG(float value) {
        internal_native_SetG(native_address, value);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUColor* nativeObject = (JGPU::WGPUColor*)this_addr;
nativeObject->SetG((float)value);
*/
    public static void internal_native_SetG(long this_addr, float value) {
        try {
            FFMHandles.internal_native_SetG__JF.invokeExact(this_addr, value);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void setB(float value) {
        internal_native_SetB(native_address, value);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUColor* nativeObject = (JGPU::WGPUColor*)this_addr;
nativeObject->SetB((float)value);
*/
    public static void internal_native_SetB(long this_addr, float value) {
        try {
            FFMHandles.internal_native_SetB__JF.invokeExact(this_addr, value);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void setA(float value) {
        internal_native_SetA(native_address, value);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUColor* nativeObject = (JGPU::WGPUColor*)this_addr;
nativeObject->SetA((float)value);
*/
    public static void internal_native_SetA(long this_addr, float value) {
        try {
            FFMHandles.internal_native_SetA__JF.invokeExact(this_addr, value);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float getR() {
        return internal_native_GetR(native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUColor* nativeObject = (JGPU::WGPUColor*)this_addr;
return nativeObject->GetR();
*/
    public static float internal_native_GetR(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetR__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float getG() {
        return internal_native_GetG(native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUColor* nativeObject = (JGPU::WGPUColor*)this_addr;
return nativeObject->GetG();
*/
    public static float internal_native_GetG(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetG__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float getB() {
        return internal_native_GetB(native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUColor* nativeObject = (JGPU::WGPUColor*)this_addr;
return nativeObject->GetB();
*/
    public static float internal_native_GetB(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetB__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float getA() {
        return internal_native_GetA(native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUColor* nativeObject = (JGPU::WGPUColor*)this_addr;
return nativeObject->GetA();
*/
    public static float internal_native_GetA(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetA__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static WGPUColor obtain() {
        long addr = internal_native_Obtain_addr();
        if (addr == 0)
            return WGPUColor.NULL;
        if (WGPUColor_TEMP_STATIC_GEN_0 == null)
            WGPUColor_TEMP_STATIC_GEN_0 = WGPUColor.native_new();
        WGPUColor_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return WGPUColor_TEMP_STATIC_GEN_0;
    }

    /*[-FFM;-NATIVE]
return (int64_t)JGPU::WGPUColor::Obtain();
*/
    public static long internal_native_Obtain_addr() {
        try {
            return (long) FFMHandles.internal_native_Obtain_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUColor_internal_1native_1create_1addr__", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUColor_internal_1native_1deleteNative__J", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetColor__JFFFF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUColor_internal_1native_1SetColor__JFFFF", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_SetR__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUColor_internal_1native_1SetR__JF", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_SetG__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUColor_internal_1native_1SetG__JF", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_SetB__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUColor_internal_1native_1SetB__JF", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_SetA__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUColor_internal_1native_1SetA__JF", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetR__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUColor_internal_1native_1GetR__J", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetG__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUColor_internal_1native_1GetG__J", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetB__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUColor_internal_1native_1GetB__J", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetA__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUColor_internal_1native_1GetA__J", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Obtain_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUColor_internal_1native_1Obtain_1addr__", FunctionDescriptor.of(ValueLayout.JAVA_LONG));
    }
}
