/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUMapAsyncStatus implements IDLEnum<WGPUMapAsyncStatus> {

    CUSTOM(0), Success(WGPUMapAsyncStatus_Success_NATIVE()), Error(WGPUMapAsyncStatus_Error_NATIVE()), Aborted(WGPUMapAsyncStatus_Aborted_NATIVE()), Force32(WGPUMapAsyncStatus_Force32_NATIVE());

    private int value;

    private WGPUMapAsyncStatus(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUMapAsyncStatus setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUMapAsyncStatus getCustom() {
        return CUSTOM;
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUMapAsyncStatus_Success;
*/
    private static int WGPUMapAsyncStatus_Success_NATIVE() {
        try {
            return (int) FFMHandles.WGPUMapAsyncStatus_Success_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUMapAsyncStatus_Error;
*/
    private static int WGPUMapAsyncStatus_Error_NATIVE() {
        try {
            return (int) FFMHandles.WGPUMapAsyncStatus_Error_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUMapAsyncStatus_Aborted;
*/
    private static int WGPUMapAsyncStatus_Aborted_NATIVE() {
        try {
            return (int) FFMHandles.WGPUMapAsyncStatus_Aborted_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUMapAsyncStatus_Force32;
*/
    private static int WGPUMapAsyncStatus_Force32_NATIVE() {
        try {
            return (int) FFMHandles.WGPUMapAsyncStatus_Force32_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP;

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static {
            LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();
        }

        static final java.lang.invoke.MethodHandle WGPUMapAsyncStatus_Success_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUMapAsyncStatus_WGPUMapAsyncStatus_1Success_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUMapAsyncStatus_Error_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUMapAsyncStatus_WGPUMapAsyncStatus_1Error_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUMapAsyncStatus_Aborted_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUMapAsyncStatus_WGPUMapAsyncStatus_1Aborted_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUMapAsyncStatus_Force32_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUMapAsyncStatus_WGPUMapAsyncStatus_1Force32_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
