/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUTextureDimension implements NativeEnum<WGPUTextureDimension> {

    CUSTOM(0),
    Undefined(WGPUTextureDimension_Undefined_NATIVE()),
    _1D(WGPUTextureDimension_1D_NATIVE()),
    _2D(WGPUTextureDimension_2D_NATIVE()),
    _3D(WGPUTextureDimension_3D_NATIVE()),
    Force32(WGPUTextureDimension_Force32_NATIVE());

    private int value;

    private WGPUTextureDimension(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUTextureDimension setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUTextureDimension getCustom() {
        return CUSTOM;
    }

    private static int WGPUTextureDimension_Undefined_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3686027994", "WGPUTextureDimension.WGPUTextureDimension_Undefined_NATIVE");
            return (int) FFMHandles.WGPUTextureDimension_Undefined_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureDimension_1D_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3700096533", "WGPUTextureDimension.WGPUTextureDimension_1D_NATIVE");
            return (int) FFMHandles.WGPUTextureDimension_1D_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureDimension_2D_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3503583028", "WGPUTextureDimension.WGPUTextureDimension_2D_NATIVE");
            return (int) FFMHandles.WGPUTextureDimension_2D_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureDimension_3D_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3307069523", "WGPUTextureDimension.WGPUTextureDimension_3D_NATIVE");
            return (int) FFMHandles.WGPUTextureDimension_3D_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureDimension_Force32_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3836259092", "WGPUTextureDimension.WGPUTextureDimension_Force32_NATIVE");
            return (int) FFMHandles.WGPUTextureDimension_Force32_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle WGPUTextureDimension_Undefined_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3686027994", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureDimension_1D_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3700096533", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureDimension_2D_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3503583028", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureDimension_3D_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3307069523", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureDimension_Force32_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3836259092", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
