/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUFeatureName implements NativeEnum<WGPUFeatureName> {

    CUSTOM(0),
    DepthClipControl(WGPUFeatureName_DepthClipControl_NATIVE()),
    Depth32FloatStencil8(WGPUFeatureName_Depth32FloatStencil8_NATIVE()),
    TimestampQuery(WGPUFeatureName_TimestampQuery_NATIVE()),
    TextureCompressionBC(WGPUFeatureName_TextureCompressionBC_NATIVE()),
    TextureCompressionBCSliced3D(WGPUFeatureName_TextureCompressionBCSliced3D_NATIVE()),
    TextureCompressionETC2(WGPUFeatureName_TextureCompressionETC2_NATIVE()),
    TextureCompressionASTC(WGPUFeatureName_TextureCompressionASTC_NATIVE()),
    TextureCompressionASTCSliced3D(WGPUFeatureName_TextureCompressionASTCSliced3D_NATIVE()),
    IndirectFirstInstance(WGPUFeatureName_IndirectFirstInstance_NATIVE()),
    ShaderF16(WGPUFeatureName_ShaderF16_NATIVE()),
    RG11B10UfloatRenderable(WGPUFeatureName_RG11B10UfloatRenderable_NATIVE()),
    BGRA8UnormStorage(WGPUFeatureName_BGRA8UnormStorage_NATIVE()),
    Float32Filterable(WGPUFeatureName_Float32Filterable_NATIVE()),
    Float32Blendable(WGPUFeatureName_Float32Blendable_NATIVE()),
    ClipDistances(WGPUFeatureName_ClipDistances_NATIVE()),
    DualSourceBlending(WGPUFeatureName_DualSourceBlending_NATIVE()),
    Force32(WGPUFeatureName_Force32_NATIVE());

    private int value;

    private WGPUFeatureName(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUFeatureName setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUFeatureName getCustom() {
        return CUSTOM;
    }

    private static int WGPUFeatureName_DepthClipControl_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_DepthClipControl_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFeatureName_Depth32FloatStencil8_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_Depth32FloatStencil8_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFeatureName_TimestampQuery_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_TimestampQuery_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFeatureName_TextureCompressionBC_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_TextureCompressionBC_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFeatureName_TextureCompressionBCSliced3D_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_TextureCompressionBCSliced3D_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFeatureName_TextureCompressionETC2_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_TextureCompressionETC2_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFeatureName_TextureCompressionASTC_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_TextureCompressionASTC_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFeatureName_TextureCompressionASTCSliced3D_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_TextureCompressionASTCSliced3D_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFeatureName_IndirectFirstInstance_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_IndirectFirstInstance_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFeatureName_ShaderF16_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_ShaderF16_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFeatureName_RG11B10UfloatRenderable_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_RG11B10UfloatRenderable_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFeatureName_BGRA8UnormStorage_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_BGRA8UnormStorage_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFeatureName_Float32Filterable_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_Float32Filterable_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFeatureName_Float32Blendable_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_Float32Blendable_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFeatureName_ClipDistances_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_ClipDistances_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFeatureName_DualSourceBlending_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_DualSourceBlending_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUFeatureName_Force32_NATIVE() {
        try {
            return (int) FFMHandles.WGPUFeatureName_Force32_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle WGPUFeatureName_DepthClipControl_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_depthclipcontrol_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFeatureName_Depth32FloatStencil8_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_depth32floatstencil8_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFeatureName_TimestampQuery_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_timestampquery_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFeatureName_TextureCompressionBC_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_texturecompressionbc_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFeatureName_TextureCompressionBCSliced3D_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_texturecompressionbcsliced3d_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFeatureName_TextureCompressionETC2_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_texturecompressionetc2_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFeatureName_TextureCompressionASTC_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_texturecompressionastc_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFeatureName_TextureCompressionASTCSliced3D_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_texturecompressionastcsliced3d_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFeatureName_IndirectFirstInstance_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_indirectfirstinstance_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFeatureName_ShaderF16_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_shaderf16_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFeatureName_RG11B10UfloatRenderable_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_rg11b10ufloatrenderable_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFeatureName_BGRA8UnormStorage_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_bgra8unormstorage_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFeatureName_Float32Filterable_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_float32filterable_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFeatureName_Float32Blendable_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_float32blendable_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFeatureName_ClipDistances_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_clipdistances_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFeatureName_DualSourceBlending_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_dualsourceblending_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUFeatureName_Force32_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpufeaturename_wgpufeaturename_force32_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
