/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUTextureFormat implements NativeEnum<WGPUTextureFormat> {

    CUSTOM(0),
    Undefined(WGPUTextureFormat_Undefined_NATIVE()),
    R8Unorm(WGPUTextureFormat_R8Unorm_NATIVE()),
    R8Snorm(WGPUTextureFormat_R8Snorm_NATIVE()),
    R8Uint(WGPUTextureFormat_R8Uint_NATIVE()),
    R8Sint(WGPUTextureFormat_R8Sint_NATIVE()),
    R16Uint(WGPUTextureFormat_R16Uint_NATIVE()),
    R16Sint(WGPUTextureFormat_R16Sint_NATIVE()),
    R16Float(WGPUTextureFormat_R16Float_NATIVE()),
    RG8Unorm(WGPUTextureFormat_RG8Unorm_NATIVE()),
    RG8Snorm(WGPUTextureFormat_RG8Snorm_NATIVE()),
    RG8Uint(WGPUTextureFormat_RG8Uint_NATIVE()),
    RG8Sint(WGPUTextureFormat_RG8Sint_NATIVE()),
    R32Float(WGPUTextureFormat_R32Float_NATIVE()),
    R32Uint(WGPUTextureFormat_R32Uint_NATIVE()),
    R32Sint(WGPUTextureFormat_R32Sint_NATIVE()),
    RG16Uint(WGPUTextureFormat_RG16Uint_NATIVE()),
    RG16Sint(WGPUTextureFormat_RG16Sint_NATIVE()),
    RG16Float(WGPUTextureFormat_RG16Float_NATIVE()),
    RGBA8Unorm(WGPUTextureFormat_RGBA8Unorm_NATIVE()),
    RGBA8UnormSrgb(WGPUTextureFormat_RGBA8UnormSrgb_NATIVE()),
    RGBA8Snorm(WGPUTextureFormat_RGBA8Snorm_NATIVE()),
    RGBA8Uint(WGPUTextureFormat_RGBA8Uint_NATIVE()),
    RGBA8Sint(WGPUTextureFormat_RGBA8Sint_NATIVE()),
    BGRA8Unorm(WGPUTextureFormat_BGRA8Unorm_NATIVE()),
    BGRA8UnormSrgb(WGPUTextureFormat_BGRA8UnormSrgb_NATIVE()),
    RGB10A2Uint(WGPUTextureFormat_RGB10A2Uint_NATIVE()),
    RGB10A2Unorm(WGPUTextureFormat_RGB10A2Unorm_NATIVE()),
    RG11B10Ufloat(WGPUTextureFormat_RG11B10Ufloat_NATIVE()),
    RGB9E5Ufloat(WGPUTextureFormat_RGB9E5Ufloat_NATIVE()),
    RG32Float(WGPUTextureFormat_RG32Float_NATIVE()),
    RG32Uint(WGPUTextureFormat_RG32Uint_NATIVE()),
    RG32Sint(WGPUTextureFormat_RG32Sint_NATIVE()),
    RGBA16Uint(WGPUTextureFormat_RGBA16Uint_NATIVE()),
    RGBA16Sint(WGPUTextureFormat_RGBA16Sint_NATIVE()),
    RGBA16Float(WGPUTextureFormat_RGBA16Float_NATIVE()),
    RGBA32Float(WGPUTextureFormat_RGBA32Float_NATIVE()),
    RGBA32Uint(WGPUTextureFormat_RGBA32Uint_NATIVE()),
    RGBA32Sint(WGPUTextureFormat_RGBA32Sint_NATIVE()),
    Stencil8(WGPUTextureFormat_Stencil8_NATIVE()),
    Depth16Unorm(WGPUTextureFormat_Depth16Unorm_NATIVE()),
    Depth24Plus(WGPUTextureFormat_Depth24Plus_NATIVE()),
    Depth24PlusStencil8(WGPUTextureFormat_Depth24PlusStencil8_NATIVE()),
    Depth32Float(WGPUTextureFormat_Depth32Float_NATIVE()),
    Depth32FloatStencil8(WGPUTextureFormat_Depth32FloatStencil8_NATIVE()),
    BC1RGBAUnorm(WGPUTextureFormat_BC1RGBAUnorm_NATIVE()),
    BC1RGBAUnormSrgb(WGPUTextureFormat_BC1RGBAUnormSrgb_NATIVE()),
    BC2RGBAUnorm(WGPUTextureFormat_BC2RGBAUnorm_NATIVE()),
    BC2RGBAUnormSrgb(WGPUTextureFormat_BC2RGBAUnormSrgb_NATIVE()),
    BC3RGBAUnorm(WGPUTextureFormat_BC3RGBAUnorm_NATIVE()),
    BC3RGBAUnormSrgb(WGPUTextureFormat_BC3RGBAUnormSrgb_NATIVE()),
    BC4RUnorm(WGPUTextureFormat_BC4RUnorm_NATIVE()),
    BC4RSnorm(WGPUTextureFormat_BC4RSnorm_NATIVE()),
    BC5RGUnorm(WGPUTextureFormat_BC5RGUnorm_NATIVE()),
    BC5RGSnorm(WGPUTextureFormat_BC5RGSnorm_NATIVE()),
    BC6HRGBUfloat(WGPUTextureFormat_BC6HRGBUfloat_NATIVE()),
    BC6HRGBFloat(WGPUTextureFormat_BC6HRGBFloat_NATIVE()),
    BC7RGBAUnorm(WGPUTextureFormat_BC7RGBAUnorm_NATIVE()),
    BC7RGBAUnormSrgb(WGPUTextureFormat_BC7RGBAUnormSrgb_NATIVE()),
    ETC2RGB8Unorm(WGPUTextureFormat_ETC2RGB8Unorm_NATIVE()),
    ETC2RGB8UnormSrgb(WGPUTextureFormat_ETC2RGB8UnormSrgb_NATIVE()),
    ETC2RGB8A1Unorm(WGPUTextureFormat_ETC2RGB8A1Unorm_NATIVE()),
    ETC2RGB8A1UnormSrgb(WGPUTextureFormat_ETC2RGB8A1UnormSrgb_NATIVE()),
    ETC2RGBA8Unorm(WGPUTextureFormat_ETC2RGBA8Unorm_NATIVE()),
    ETC2RGBA8UnormSrgb(WGPUTextureFormat_ETC2RGBA8UnormSrgb_NATIVE()),
    EACR11Unorm(WGPUTextureFormat_EACR11Unorm_NATIVE()),
    EACR11Snorm(WGPUTextureFormat_EACR11Snorm_NATIVE()),
    EACRG11Unorm(WGPUTextureFormat_EACRG11Unorm_NATIVE()),
    EACRG11Snorm(WGPUTextureFormat_EACRG11Snorm_NATIVE()),
    ASTC4x4Unorm(WGPUTextureFormat_ASTC4x4Unorm_NATIVE()),
    ASTC4x4UnormSrgb(WGPUTextureFormat_ASTC4x4UnormSrgb_NATIVE()),
    ASTC5x4Unorm(WGPUTextureFormat_ASTC5x4Unorm_NATIVE()),
    ASTC5x4UnormSrgb(WGPUTextureFormat_ASTC5x4UnormSrgb_NATIVE()),
    ASTC5x5Unorm(WGPUTextureFormat_ASTC5x5Unorm_NATIVE()),
    ASTC5x5UnormSrgb(WGPUTextureFormat_ASTC5x5UnormSrgb_NATIVE()),
    ASTC6x5Unorm(WGPUTextureFormat_ASTC6x5Unorm_NATIVE()),
    ASTC6x5UnormSrgb(WGPUTextureFormat_ASTC6x5UnormSrgb_NATIVE()),
    ASTC6x6Unorm(WGPUTextureFormat_ASTC6x6Unorm_NATIVE()),
    ASTC6x6UnormSrgb(WGPUTextureFormat_ASTC6x6UnormSrgb_NATIVE()),
    ASTC8x5Unorm(WGPUTextureFormat_ASTC8x5Unorm_NATIVE()),
    ASTC8x5UnormSrgb(WGPUTextureFormat_ASTC8x5UnormSrgb_NATIVE()),
    ASTC8x6Unorm(WGPUTextureFormat_ASTC8x6Unorm_NATIVE()),
    ASTC8x6UnormSrgb(WGPUTextureFormat_ASTC8x6UnormSrgb_NATIVE()),
    ASTC8x8Unorm(WGPUTextureFormat_ASTC8x8Unorm_NATIVE()),
    ASTC8x8UnormSrgb(WGPUTextureFormat_ASTC8x8UnormSrgb_NATIVE()),
    ASTC10x5Unorm(WGPUTextureFormat_ASTC10x5Unorm_NATIVE()),
    ASTC10x5UnormSrgb(WGPUTextureFormat_ASTC10x5UnormSrgb_NATIVE()),
    ASTC10x6Unorm(WGPUTextureFormat_ASTC10x6Unorm_NATIVE()),
    ASTC10x6UnormSrgb(WGPUTextureFormat_ASTC10x6UnormSrgb_NATIVE()),
    ASTC10x8Unorm(WGPUTextureFormat_ASTC10x8Unorm_NATIVE()),
    ASTC10x8UnormSrgb(WGPUTextureFormat_ASTC10x8UnormSrgb_NATIVE()),
    ASTC10x10Unorm(WGPUTextureFormat_ASTC10x10Unorm_NATIVE()),
    ASTC10x10UnormSrgb(WGPUTextureFormat_ASTC10x10UnormSrgb_NATIVE()),
    ASTC12x10Unorm(WGPUTextureFormat_ASTC12x10Unorm_NATIVE()),
    ASTC12x10UnormSrgb(WGPUTextureFormat_ASTC12x10UnormSrgb_NATIVE()),
    ASTC12x12Unorm(WGPUTextureFormat_ASTC12x12Unorm_NATIVE()),
    ASTC12x12UnormSrgb(WGPUTextureFormat_ASTC12x12UnormSrgb_NATIVE()),
    Force32(WGPUTextureFormat_Force32_NATIVE());

    private int value;

    private WGPUTextureFormat(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUTextureFormat setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUTextureFormat getCustom() {
        return CUSTOM;
    }

    private static int WGPUTextureFormat_Undefined_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2665435932", "WGPUTextureFormat.WGPUTextureFormat_Undefined_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_Undefined_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_R8Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1039090583", "WGPUTextureFormat.WGPUTextureFormat_R8Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_R8Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_R8Snorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1625896597", "WGPUTextureFormat.WGPUTextureFormat_R8Snorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_R8Snorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_R8Uint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2195973760", "WGPUTextureFormat.WGPUTextureFormat_R8Uint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_R8Uint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_R8Sint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1937808322", "WGPUTextureFormat.WGPUTextureFormat_R8Sint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_R8Sint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_R16Uint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n772072541", "WGPUTextureFormat.WGPUTextureFormat_R16Uint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_R16Uint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_R16Sint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n513907103", "WGPUTextureFormat.WGPUTextureFormat_R16Sint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_R16Sint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_R16Float_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3269188357", "WGPUTextureFormat.WGPUTextureFormat_R16Float_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_R16Float_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RG8Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1938077230", "WGPUTextureFormat.WGPUTextureFormat_RG8Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RG8Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RG8Snorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2524883244", "WGPUTextureFormat.WGPUTextureFormat_RG8Snorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RG8Snorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RG8Uint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1947878665", "WGPUTextureFormat.WGPUTextureFormat_RG8Uint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RG8Uint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RG8Sint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1689713227", "WGPUTextureFormat.WGPUTextureFormat_RG8Sint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RG8Sint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_R32Float_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n4011559179", "WGPUTextureFormat.WGPUTextureFormat_R32Float_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_R32Float_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_R32Uint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n934567319", "WGPUTextureFormat.WGPUTextureFormat_R32Uint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_R32Uint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_R32Sint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n676401881", "WGPUTextureFormat.WGPUTextureFormat_R32Sint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_R32Sint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RG16Uint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1671059188", "WGPUTextureFormat.WGPUTextureFormat_RG16Uint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RG16Uint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RG16Sint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1412893750", "WGPUTextureFormat.WGPUTextureFormat_RG16Sint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RG16Sint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RG16Float_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1073003342", "WGPUTextureFormat.WGPUTextureFormat_RG16Float_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RG16Float_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RGBA8Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2476928109", "WGPUTextureFormat.WGPUTextureFormat_RGBA8Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RGBA8Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RGBA8UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n638229127", "WGPUTextureFormat.WGPUTextureFormat_RGBA8UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RGBA8UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RGBA8Snorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3063734123", "WGPUTextureFormat.WGPUTextureFormat_RGBA8Snorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RGBA8Snorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RGBA8Uint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n441240298", "WGPUTextureFormat.WGPUTextureFormat_RGBA8Uint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RGBA8Uint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RGBA8Sint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n183074860", "WGPUTextureFormat.WGPUTextureFormat_RGBA8Sint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RGBA8Sint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_BGRA8Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1671604333", "WGPUTextureFormat.WGPUTextureFormat_BGRA8Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_BGRA8Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_BGRA8UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n936138375", "WGPUTextureFormat.WGPUTextureFormat_BGRA8UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_BGRA8UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RGB10A2Uint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n4233617155", "WGPUTextureFormat.WGPUTextureFormat_RGB10A2Uint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RGB10A2Uint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RGB10A2Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n4076493684", "WGPUTextureFormat.WGPUTextureFormat_RGB10A2Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RGB10A2Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RG11B10Ufloat_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2235321535", "WGPUTextureFormat.WGPUTextureFormat_RG11B10Ufloat_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RG11B10Ufloat_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RGB9E5Ufloat_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1083752003", "WGPUTextureFormat.WGPUTextureFormat_RGB9E5Ufloat_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RGB9E5Ufloat_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RG32Float_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1815374164", "WGPUTextureFormat.WGPUTextureFormat_RG32Float_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RG32Float_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RG32Uint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1833553966", "WGPUTextureFormat.WGPUTextureFormat_RG32Uint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RG32Uint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RG32Sint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1575388528", "WGPUTextureFormat.WGPUTextureFormat_RG32Sint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RG32Sint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RGBA16Uint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2209910067", "WGPUTextureFormat.WGPUTextureFormat_RGBA16Uint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RGBA16Uint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RGBA16Sint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1951744629", "WGPUTextureFormat.WGPUTextureFormat_RGBA16Sint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RGBA16Sint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RGBA16Float_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n597511407", "WGPUTextureFormat.WGPUTextureFormat_RGBA16Float_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RGBA16Float_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RGBA32Float_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1339882229", "WGPUTextureFormat.WGPUTextureFormat_RGBA32Float_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RGBA32Float_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RGBA32Uint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2372404845", "WGPUTextureFormat.WGPUTextureFormat_RGBA32Uint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RGBA32Uint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_RGBA32Sint_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2114239407", "WGPUTextureFormat.WGPUTextureFormat_RGBA32Sint_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_RGBA32Sint_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_Stencil8_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3784206204", "WGPUTextureFormat.WGPUTextureFormat_Stencil8_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_Stencil8_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_Depth16Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n309124585", "WGPUTextureFormat.WGPUTextureFormat_Depth16Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_Depth16Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_Depth24Plus_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1221328075", "WGPUTextureFormat.WGPUTextureFormat_Depth24Plus_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_Depth24Plus_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_Depth24PlusStencil8_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3321371111", "WGPUTextureFormat.WGPUTextureFormat_Depth24PlusStencil8_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_Depth24PlusStencil8_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_Depth32Float_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n177890714", "WGPUTextureFormat.WGPUTextureFormat_Depth32Float_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_Depth32Float_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_Depth32FloatStencil8_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2318681014", "WGPUTextureFormat.WGPUTextureFormat_Depth32FloatStencil8_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_Depth32FloatStencil8_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_BC1RGBAUnorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1952330285", "WGPUTextureFormat.WGPUTextureFormat_BC1RGBAUnorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_BC1RGBAUnorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_BC1RGBAUnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n137166919", "WGPUTextureFormat.WGPUTextureFormat_BC1RGBAUnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_BC1RGBAUnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_BC2RGBAUnorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n955257932", "WGPUTextureFormat.WGPUTextureFormat_BC2RGBAUnorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_BC2RGBAUnorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_BC2RGBAUnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2394077926", "WGPUTextureFormat.WGPUTextureFormat_BC2RGBAUnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_BC2RGBAUnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_BC3RGBAUnorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n4253152875", "WGPUTextureFormat.WGPUTextureFormat_BC3RGBAUnorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_BC3RGBAUnorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_BC3RGBAUnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n356021637", "WGPUTextureFormat.WGPUTextureFormat_BC3RGBAUnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_BC3RGBAUnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_BC4RUnorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2767574590", "WGPUTextureFormat.WGPUTextureFormat_BC4RUnorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_BC4RUnorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_BC4RSnorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3354380604", "WGPUTextureFormat.WGPUTextureFormat_BC4RSnorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_BC4RSnorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_BC5RGUnorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3339054280", "WGPUTextureFormat.WGPUTextureFormat_BC5RGUnorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_BC5RGUnorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_BC5RGSnorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3925860294", "WGPUTextureFormat.WGPUTextureFormat_BC5RGSnorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_BC5RGSnorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_BC6HRGBUfloat_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2301181581", "WGPUTextureFormat.WGPUTextureFormat_BC6HRGBUfloat_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_BC6HRGBUfloat_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_BC6HRGBFloat_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1156460514", "WGPUTextureFormat.WGPUTextureFormat_BC6HRGBFloat_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_BC6HRGBFloat_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_BC7RGBAUnorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n264863463", "WGPUTextureFormat.WGPUTextureFormat_BC7RGBAUnorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_BC7RGBAUnorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_BC7RGBAUnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n793731073", "WGPUTextureFormat.WGPUTextureFormat_BC7RGBAUnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_BC7RGBAUnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ETC2RGB8Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1801609908", "WGPUTextureFormat.WGPUTextureFormat_ETC2RGB8Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ETC2RGB8Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ETC2RGB8UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2298975566", "WGPUTextureFormat.WGPUTextureFormat_ETC2RGB8UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ETC2RGB8UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ETC2RGB8A1Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n235168100", "WGPUTextureFormat.WGPUTextureFormat_ETC2RGB8A1Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ETC2RGB8A1Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ETC2RGB8A1UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n4163550206", "WGPUTextureFormat.WGPUTextureFormat_ETC2RGB8A1UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ETC2RGB8A1UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ETC2RGBA8Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3645963563", "WGPUTextureFormat.WGPUTextureFormat_ETC2RGBA8Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ETC2RGBA8Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ETC2RGBA8UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3500547141", "WGPUTextureFormat.WGPUTextureFormat_ETC2RGBA8UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ETC2RGBA8UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_EACR11Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n748804466", "WGPUTextureFormat.WGPUTextureFormat_EACR11Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_EACR11Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_EACR11Snorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1335610480", "WGPUTextureFormat.WGPUTextureFormat_EACR11Snorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_EACR11Snorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_EACRG11Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1287794613", "WGPUTextureFormat.WGPUTextureFormat_EACRG11Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_EACRG11Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_EACRG11Snorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1874600627", "WGPUTextureFormat.WGPUTextureFormat_EACRG11Snorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_EACRG11Snorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC4x4Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1267864866", "WGPUTextureFormat.WGPUTextureFormat_ASTC4x4Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC4x4Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC4x4UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2350670012", "WGPUTextureFormat.WGPUTextureFormat_ASTC4x4UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC4x4UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC5x4Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n757330689", "WGPUTextureFormat.WGPUTextureFormat_ASTC5x4Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC5x4Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC5x4UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1941845787", "WGPUTextureFormat.WGPUTextureFormat_ASTC5x4UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC5x4UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC5x5Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n251772064", "WGPUTextureFormat.WGPUTextureFormat_ASTC5x5Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC5x5Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC5x5UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n944773434", "WGPUTextureFormat.WGPUTextureFormat_ASTC5x5UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC5x5UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC6x5Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n4036205183", "WGPUTextureFormat.WGPUTextureFormat_ASTC6x5Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC6x5Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC6x5UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n535949209", "WGPUTextureFormat.WGPUTextureFormat_ASTC6x5UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC6x5UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC6x6Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3530646558", "WGPUTextureFormat.WGPUTextureFormat_ASTC6x6Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC6x6Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC6x6UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3833844152", "WGPUTextureFormat.WGPUTextureFormat_ASTC6x6UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC6x6UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC8x5Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3015136829", "WGPUTextureFormat.WGPUTextureFormat_ASTC8x5Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC8x5Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC8x5UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n4013268055", "WGPUTextureFormat.WGPUTextureFormat_ASTC8x5UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC8x5UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC8x6Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2509578204", "WGPUTextureFormat.WGPUTextureFormat_ASTC8x6Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC8x6Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC8x6UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3016195702", "WGPUTextureFormat.WGPUTextureFormat_ASTC8x6UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC8x6UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC8x8Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1498460954", "WGPUTextureFormat.WGPUTextureFormat_ASTC8x8Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC8x8Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC8x8UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1022050996", "WGPUTextureFormat.WGPUTextureFormat_ASTC8x8UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC8x8UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC10x5Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2886449120", "WGPUTextureFormat.WGPUTextureFormat_ASTC10x5Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC10x5Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC10x5UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n4251612282", "WGPUTextureFormat.WGPUTextureFormat_ASTC10x5UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC10x5UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC10x6Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2380890495", "WGPUTextureFormat.WGPUTextureFormat_ASTC10x6Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC10x6Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC10x6UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3254539929", "WGPUTextureFormat.WGPUTextureFormat_ASTC10x6UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC10x6UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC10x8Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1369773245", "WGPUTextureFormat.WGPUTextureFormat_ASTC10x8Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC10x8Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC10x8UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1260395223", "WGPUTextureFormat.WGPUTextureFormat_ASTC10x8UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC10x8UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC10x10Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n247438138", "WGPUTextureFormat.WGPUTextureFormat_ASTC10x10Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC10x10Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC10x10UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1382619860", "WGPUTextureFormat.WGPUTextureFormat_ASTC10x10UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC10x10UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC12x10Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2954057532", "WGPUTextureFormat.WGPUTextureFormat_ASTC12x10Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC12x10Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC12x10UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1805321686", "WGPUTextureFormat.WGPUTextureFormat_ASTC12x10UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC12x10UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC12x12Unorm_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1942940282", "WGPUTextureFormat.WGPUTextureFormat_ASTC12x12Unorm_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC12x12Unorm_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_ASTC12x12UnormSrgb_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n4106144276", "WGPUTextureFormat.WGPUTextureFormat_ASTC12x12UnormSrgb_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_ASTC12x12UnormSrgb_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUTextureFormat_Force32_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n599446486", "WGPUTextureFormat.WGPUTextureFormat_Force32_NATIVE");
            return (int) FFMHandles.WGPUTextureFormat_Force32_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_Undefined_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2665435932", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_R8Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1039090583", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_R8Snorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1625896597", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_R8Uint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2195973760", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_R8Sint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1937808322", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_R16Uint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n772072541", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_R16Sint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n513907103", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_R16Float_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3269188357", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RG8Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1938077230", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RG8Snorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2524883244", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RG8Uint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1947878665", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RG8Sint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1689713227", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_R32Float_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n4011559179", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_R32Uint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n934567319", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_R32Sint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n676401881", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RG16Uint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1671059188", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RG16Sint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1412893750", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RG16Float_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1073003342", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RGBA8Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2476928109", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RGBA8UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n638229127", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RGBA8Snorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3063734123", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RGBA8Uint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n441240298", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RGBA8Sint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n183074860", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_BGRA8Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1671604333", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_BGRA8UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n936138375", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RGB10A2Uint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n4233617155", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RGB10A2Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n4076493684", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RG11B10Ufloat_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2235321535", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RGB9E5Ufloat_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1083752003", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RG32Float_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1815374164", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RG32Uint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1833553966", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RG32Sint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1575388528", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RGBA16Uint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2209910067", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RGBA16Sint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1951744629", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RGBA16Float_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n597511407", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RGBA32Float_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1339882229", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RGBA32Uint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2372404845", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_RGBA32Sint_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2114239407", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_Stencil8_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3784206204", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_Depth16Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n309124585", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_Depth24Plus_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1221328075", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_Depth24PlusStencil8_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3321371111", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_Depth32Float_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n177890714", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_Depth32FloatStencil8_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2318681014", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_BC1RGBAUnorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1952330285", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_BC1RGBAUnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n137166919", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_BC2RGBAUnorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n955257932", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_BC2RGBAUnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2394077926", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_BC3RGBAUnorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n4253152875", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_BC3RGBAUnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n356021637", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_BC4RUnorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2767574590", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_BC4RSnorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3354380604", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_BC5RGUnorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3339054280", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_BC5RGSnorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3925860294", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_BC6HRGBUfloat_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2301181581", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_BC6HRGBFloat_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1156460514", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_BC7RGBAUnorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n264863463", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_BC7RGBAUnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n793731073", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ETC2RGB8Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1801609908", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ETC2RGB8UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2298975566", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ETC2RGB8A1Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n235168100", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ETC2RGB8A1UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n4163550206", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ETC2RGBA8Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3645963563", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ETC2RGBA8UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3500547141", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_EACR11Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n748804466", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_EACR11Snorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1335610480", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_EACRG11Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1287794613", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_EACRG11Snorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1874600627", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC4x4Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1267864866", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC4x4UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2350670012", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC5x4Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n757330689", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC5x4UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1941845787", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC5x5Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n251772064", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC5x5UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n944773434", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC6x5Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n4036205183", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC6x5UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n535949209", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC6x6Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3530646558", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC6x6UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3833844152", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC8x5Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3015136829", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC8x5UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n4013268055", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC8x6Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2509578204", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC8x6UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3016195702", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC8x8Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1498460954", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC8x8UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1022050996", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC10x5Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2886449120", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC10x5UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n4251612282", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC10x6Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2380890495", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC10x6UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3254539929", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC10x8Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1369773245", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC10x8UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1260395223", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC10x10Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n247438138", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC10x10UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1382619860", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC12x10Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2954057532", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC12x10UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1805321686", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC12x12Unorm_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1942940282", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_ASTC12x12UnormSrgb_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n4106144276", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureFormat_Force32_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n599446486", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
