/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUTextureUsage implements IDLEnum<WGPUTextureUsage> {

    CUSTOM(0),
    None(WGPUTextureUsage_None_NATIVE()),
    CopySrc(WGPUTextureUsage_CopySrc_NATIVE()),
    CopyDst(WGPUTextureUsage_CopyDst_NATIVE()),
    TextureBinding(WGPUTextureUsage_TextureBinding_NATIVE()),
    StorageBinding(WGPUTextureUsage_StorageBinding_NATIVE()),
    RenderAttachment(WGPUTextureUsage_RenderAttachment_NATIVE());

    private int value;

    private WGPUTextureUsage(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUTextureUsage setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUTextureUsage getCustom() {
        return CUSTOM;
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUTextureUsage_None;
*/
    private static int WGPUTextureUsage_None_NATIVE() {
        try {
            return (int) FFMHandles.WGPUTextureUsage_None_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUTextureUsage_CopySrc;
*/
    private static int WGPUTextureUsage_CopySrc_NATIVE() {
        try {
            return (int) FFMHandles.WGPUTextureUsage_CopySrc_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUTextureUsage_CopyDst;
*/
    private static int WGPUTextureUsage_CopyDst_NATIVE() {
        try {
            return (int) FFMHandles.WGPUTextureUsage_CopyDst_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUTextureUsage_TextureBinding;
*/
    private static int WGPUTextureUsage_TextureBinding_NATIVE() {
        try {
            return (int) FFMHandles.WGPUTextureUsage_TextureBinding_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUTextureUsage_StorageBinding;
*/
    private static int WGPUTextureUsage_StorageBinding_NATIVE() {
        try {
            return (int) FFMHandles.WGPUTextureUsage_StorageBinding_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUTextureUsage_RenderAttachment;
*/
    private static int WGPUTextureUsage_RenderAttachment_NATIVE() {
        try {
            return (int) FFMHandles.WGPUTextureUsage_RenderAttachment_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP;

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static {
            LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();
        }

        static final java.lang.invoke.MethodHandle WGPUTextureUsage_None_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUTextureUsage_WGPUTextureUsage_1None_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureUsage_CopySrc_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUTextureUsage_WGPUTextureUsage_1CopySrc_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureUsage_CopyDst_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUTextureUsage_WGPUTextureUsage_1CopyDst_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureUsage_TextureBinding_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUTextureUsage_WGPUTextureUsage_1TextureBinding_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureUsage_StorageBinding_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUTextureUsage_WGPUTextureUsage_1StorageBinding_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUTextureUsage_RenderAttachment_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUTextureUsage_WGPUTextureUsage_1RenderAttachment_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
