/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUCreatePipelineAsyncStatus implements NativeEnum<WGPUCreatePipelineAsyncStatus> {

    CUSTOM(0), Success(WGPUCreatePipelineAsyncStatus_Success_NATIVE()), ValidationError(WGPUCreatePipelineAsyncStatus_ValidationError_NATIVE()), InternalError(WGPUCreatePipelineAsyncStatus_InternalError_NATIVE()), Force32(WGPUCreatePipelineAsyncStatus_Force32_NATIVE());

    private int value;

    private WGPUCreatePipelineAsyncStatus(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUCreatePipelineAsyncStatus setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUCreatePipelineAsyncStatus getCustom() {
        return CUSTOM;
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUCreatePipelineAsyncStatus_Success;
*/
    private static int WGPUCreatePipelineAsyncStatus_Success_NATIVE() {
        try {
            return (int) FFMHandles.WGPUCreatePipelineAsyncStatus_Success_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUCreatePipelineAsyncStatus_ValidationError;
*/
    private static int WGPUCreatePipelineAsyncStatus_ValidationError_NATIVE() {
        try {
            return (int) FFMHandles.WGPUCreatePipelineAsyncStatus_ValidationError_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUCreatePipelineAsyncStatus_InternalError;
*/
    private static int WGPUCreatePipelineAsyncStatus_InternalError_NATIVE() {
        try {
            return (int) FFMHandles.WGPUCreatePipelineAsyncStatus_InternalError_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUCreatePipelineAsyncStatus_Force32;
*/
    private static int WGPUCreatePipelineAsyncStatus_Force32_NATIVE() {
        try {
            return (int) FFMHandles.WGPUCreatePipelineAsyncStatus_Force32_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle WGPUCreatePipelineAsyncStatus_Success_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUCreatePipelineAsyncStatus_WGPUCreatePipelineAsyncStatus_1Success_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUCreatePipelineAsyncStatus_ValidationError_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUCreatePipelineAsyncStatus_WGPUCreatePipelineAsyncStatus_1ValidationError_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUCreatePipelineAsyncStatus_InternalError_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUCreatePipelineAsyncStatus_WGPUCreatePipelineAsyncStatus_1InternalError_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUCreatePipelineAsyncStatus_Force32_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUCreatePipelineAsyncStatus_WGPUCreatePipelineAsyncStatus_1Force32_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
