/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class WGPUTextureBindingLayout extends NativeObject {

    static private WGPUTextureBindingLayout WGPUTextureBindingLayout_TEMP_STATIC_GEN_0;

    static public final WGPUTextureBindingLayout NULL = WGPUTextureBindingLayout.native_new();

    public WGPUTextureBindingLayout() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n310370856", "WGPUTextureBindingLayout.internal_native_create_addr");
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUTextureBindingLayout(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUTextureBindingLayout native_new() {
        return new WGPUTextureBindingLayout((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2230611990", "WGPUTextureBindingLayout.internal_native_deleteNative");
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void setNextInChain(WGPUChainedStruct chainedStruct) {
        internal_native_SetNextInChain(native_address, chainedStruct.native_address);
    }

    public static void internal_native_SetNextInChain(long this_addr, long chainedStruct_addr) {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2780553975", "WGPUTextureBindingLayout.internal_native_SetNextInChain");
            FFMHandles.internal_native_SetNextInChain__JJ.invokeExact(this_addr, chainedStruct_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void setSampleType(WGPUTextureSampleType sampleType) {
        internal_native_SetSampleType(native_address, sampleType.getValue());
    }

    public static void internal_native_SetSampleType(long this_addr, int sampleType) {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1629783701", "WGPUTextureBindingLayout.internal_native_SetSampleType");
            FFMHandles.internal_native_SetSampleType__JI.invokeExact(this_addr, sampleType);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void setViewDimension(WGPUTextureViewDimension viewDimension) {
        internal_native_SetViewDimension(native_address, viewDimension.getValue());
    }

    public static void internal_native_SetViewDimension(long this_addr, int viewDimension) {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n92462204", "WGPUTextureBindingLayout.internal_native_SetViewDimension");
            FFMHandles.internal_native_SetViewDimension__JI.invokeExact(this_addr, viewDimension);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void setMultisampled(int multisampled) {
        internal_native_SetMultisampled(native_address, multisampled);
    }

    public static void internal_native_SetMultisampled(long this_addr, int multisampled) {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n467104536", "WGPUTextureBindingLayout.internal_native_SetMultisampled");
            FFMHandles.internal_native_SetMultisampled__JI.invokeExact(this_addr, multisampled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static WGPUTextureBindingLayout obtain() {
        long addr = internal_native_Obtain_addr();
        if (addr == 0)
            return WGPUTextureBindingLayout.NULL;
        if (WGPUTextureBindingLayout_TEMP_STATIC_GEN_0 == null)
            WGPUTextureBindingLayout_TEMP_STATIC_GEN_0 = WGPUTextureBindingLayout.native_new();
        WGPUTextureBindingLayout_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return WGPUTextureBindingLayout_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_Obtain_addr() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3758920497", "WGPUTextureBindingLayout.internal_native_Obtain_addr");
            return (long) FFMHandles.internal_native_Obtain_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n310370856", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2230611990", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetNextInChain__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2780553975", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetSampleType__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1629783701", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_SetViewDimension__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n92462204", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_SetMultisampled__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n467104536", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_Obtain_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3758920497", FunctionDescriptor.of(ValueLayout.JAVA_LONG));
    }
}
