/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class WGPUBlendState extends NativeObject {

    private WGPUBlendComponent WGPUBlendComponent_TEMP_GEN_0;

    private WGPUBlendComponent WGPUBlendComponent_TEMP_GEN_1;

    static private WGPUBlendState WGPUBlendState_TEMP_STATIC_GEN_0;

    static public final WGPUBlendState NULL = WGPUBlendState.native_new();

    public WGPUBlendState() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUBlendState(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUBlendState native_new() {
        return new WGPUBlendState((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public WGPUBlendComponent getColor() {
        long addr = internal_native_GetColor_addr(native_address);
        if (addr == 0)
            return WGPUBlendComponent.NULL;
        if (WGPUBlendComponent_TEMP_GEN_0 == null)
            WGPUBlendComponent_TEMP_GEN_0 = WGPUBlendComponent.native_new();
        WGPUBlendComponent_TEMP_GEN_0.internal_reset(addr, false);
        return WGPUBlendComponent_TEMP_GEN_0;
    }

    public static long internal_native_GetColor_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetColor_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public WGPUBlendComponent getAlpha() {
        long addr = internal_native_GetAlpha_addr(native_address);
        if (addr == 0)
            return WGPUBlendComponent.NULL;
        if (WGPUBlendComponent_TEMP_GEN_1 == null)
            WGPUBlendComponent_TEMP_GEN_1 = WGPUBlendComponent.native_new();
        WGPUBlendComponent_TEMP_GEN_1.internal_reset(addr, false);
        return WGPUBlendComponent_TEMP_GEN_1;
    }

    public static long internal_native_GetAlpha_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetAlpha_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static WGPUBlendState obtain() {
        long addr = internal_native_Obtain_addr();
        if (addr == 0)
            return WGPUBlendState.NULL;
        if (WGPUBlendState_TEMP_STATIC_GEN_0 == null)
            WGPUBlendState_TEMP_STATIC_GEN_0 = WGPUBlendState.native_new();
        WGPUBlendState_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return WGPUBlendState_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_Obtain_addr() {
        try {
            return (long) FFMHandles.internal_native_Obtain_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n663878172", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2868326562", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetColor_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1259605289", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetAlpha_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2462355812", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Obtain_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n4112427813", FunctionDescriptor.of(ValueLayout.JAVA_LONG));
    }
}
