/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class WGPUBindGroupLayoutDescriptor extends IDLBase {

    static private WGPUBindGroupLayoutDescriptor WGPUBindGroupLayoutDescriptor_TEMP_STATIC_GEN_0;

    static public final WGPUBindGroupLayoutDescriptor NULL = WGPUBindGroupLayoutDescriptor.native_new();

    public WGPUBindGroupLayoutDescriptor() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    /*[-FFM;-NATIVE]
return (int64_t)new JGPU::WGPUBindGroupLayoutDescriptor();
*/
    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUBindGroupLayoutDescriptor(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUBindGroupLayoutDescriptor native_new() {
        return new WGPUBindGroupLayoutDescriptor((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUBindGroupLayoutDescriptor* nativeObject = (JGPU::WGPUBindGroupLayoutDescriptor*)this_addr;
delete nativeObject;
*/
    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void setLabel(String label) {
        internal_native_SetLabel(native_address, label);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUBindGroupLayoutDescriptor* nativeObject = (JGPU::WGPUBindGroupLayoutDescriptor*)this_addr;
nativeObject->SetLabel(label);
*/
    public static void internal_native_SetLabel(long this_addr, String label) {
        try {
            FFMHandles.internal_native_SetLabel__JLjava_lang_String_2.invokeExact(this_addr, (java.lang.foreign.MemorySegment) (label != null ? java.lang.foreign.Arena.global().allocateFrom(label) : java.lang.foreign.MemorySegment.NULL));
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void setNextInChain(WGPUChainedStruct chainedStruct) {
        internal_native_SetNextInChain(native_address, chainedStruct.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUBindGroupLayoutDescriptor* nativeObject = (JGPU::WGPUBindGroupLayoutDescriptor*)this_addr;
nativeObject->SetNextInChain((JGPU::WGPUChainedStruct* )chainedStruct_addr);
*/
    public static void internal_native_SetNextInChain(long this_addr, long chainedStruct_addr) {
        try {
            FFMHandles.internal_native_SetNextInChain__JJ.invokeExact(this_addr, chainedStruct_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void setEntries(WGPUVectorBindGroupLayoutEntry entries) {
        internal_native_SetEntries(native_address, entries.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUBindGroupLayoutDescriptor* nativeObject = (JGPU::WGPUBindGroupLayoutDescriptor*)this_addr;
nativeObject->SetEntries((JGPU::WGPUVectorBindGroupLayoutEntry* )entries_addr);
*/
    public static void internal_native_SetEntries(long this_addr, long entries_addr) {
        try {
            FFMHandles.internal_native_SetEntries__JJ.invokeExact(this_addr, entries_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public static WGPUBindGroupLayoutDescriptor obtain() {
        long addr = internal_native_Obtain_addr();
        if (addr == 0)
            return WGPUBindGroupLayoutDescriptor.NULL;
        if (WGPUBindGroupLayoutDescriptor_TEMP_STATIC_GEN_0 == null)
            WGPUBindGroupLayoutDescriptor_TEMP_STATIC_GEN_0 = WGPUBindGroupLayoutDescriptor.native_new();
        WGPUBindGroupLayoutDescriptor_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return WGPUBindGroupLayoutDescriptor_TEMP_STATIC_GEN_0;
    }

    /*[-FFM;-NATIVE]
return (int64_t)JGPU::WGPUBindGroupLayoutDescriptor::Obtain();
*/
    public static long internal_native_Obtain_addr() {
        try {
            return (long) FFMHandles.internal_native_Obtain_addr__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP;

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static {
            LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();
        }

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUBindGroupLayoutDescriptor_internal_1native_1create_1addr__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUBindGroupLayoutDescriptor_internal_1native_1deleteNative__J").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLabel__JLjava_lang_String_2 = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUBindGroupLayoutDescriptor_internal_1native_1SetLabel__JLjava_lang_String_2").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_SetNextInChain__JJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUBindGroupLayoutDescriptor_internal_1native_1SetNextInChain__JJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEntries__JJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUBindGroupLayoutDescriptor_internal_1native_1SetEntries__JJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Obtain_addr__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUBindGroupLayoutDescriptor_internal_1native_1Obtain_1addr__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_LONG));
    }
}
