/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUDeviceLostReason implements NativeEnum<WGPUDeviceLostReason> {

    CUSTOM(0), Unknown(WGPUDeviceLostReason_Unknown_NATIVE()), Destroyed(WGPUDeviceLostReason_Destroyed_NATIVE()), FailedCreation(WGPUDeviceLostReason_FailedCreation_NATIVE()), Force32(WGPUDeviceLostReason_Force32_NATIVE());

    private int value;

    private WGPUDeviceLostReason(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUDeviceLostReason setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUDeviceLostReason getCustom() {
        return CUSTOM;
    }

    private static int WGPUDeviceLostReason_Unknown_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1161476788", "WGPUDeviceLostReason.WGPUDeviceLostReason_Unknown_NATIVE");
            return (int) FFMHandles.WGPUDeviceLostReason_Unknown_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUDeviceLostReason_Destroyed_NATIVE() {
        try {
            return (int) FFMHandles.WGPUDeviceLostReason_Destroyed_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUDeviceLostReason_FailedCreation_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n759626078", "WGPUDeviceLostReason.WGPUDeviceLostReason_FailedCreation_NATIVE");
            return (int) FFMHandles.WGPUDeviceLostReason_FailedCreation_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUDeviceLostReason_Force32_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2679460084", "WGPUDeviceLostReason.WGPUDeviceLostReason_Force32_NATIVE");
            return (int) FFMHandles.WGPUDeviceLostReason_Force32_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle WGPUDeviceLostReason_Unknown_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1161476788", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUDeviceLostReason_Destroyed_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("n4274150531", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUDeviceLostReason_FailedCreation_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n759626078", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUDeviceLostReason_Force32_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2679460084", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
