/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUAdapterType implements NativeEnum<WGPUAdapterType> {

    CUSTOM(0),
    DiscreteGPU(WGPUAdapterType_DiscreteGPU_NATIVE()),
    IntegratedGPU(WGPUAdapterType_IntegratedGPU_NATIVE()),
    CPU(WGPUAdapterType_CPU_NATIVE()),
    Unknown(WGPUAdapterType_Unknown_NATIVE()),
    Force32(WGPUAdapterType_Force32_NATIVE());

    private int value;

    private WGPUAdapterType(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUAdapterType setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUAdapterType getCustom() {
        return CUSTOM;
    }

    private static int WGPUAdapterType_DiscreteGPU_NATIVE() {
        try {
            return (int) FFMHandles.WGPUAdapterType_DiscreteGPU_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUAdapterType_IntegratedGPU_NATIVE() {
        try {
            return (int) FFMHandles.WGPUAdapterType_IntegratedGPU_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUAdapterType_CPU_NATIVE() {
        try {
            return (int) FFMHandles.WGPUAdapterType_CPU_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUAdapterType_Unknown_NATIVE() {
        try {
            return (int) FFMHandles.WGPUAdapterType_Unknown_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUAdapterType_Force32_NATIVE() {
        try {
            return (int) FFMHandles.WGPUAdapterType_Force32_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle WGPUAdapterType_DiscreteGPU_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpuadaptertype_wgpuadaptertype_discretegpu_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUAdapterType_IntegratedGPU_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpuadaptertype_wgpuadaptertype_integratedgpu_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUAdapterType_CPU_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpuadaptertype_wgpuadaptertype_cpu_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUAdapterType_Unknown_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpuadaptertype_wgpuadaptertype_unknown_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUAdapterType_Force32_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpuadaptertype_wgpuadaptertype_force32_native", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
