/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class WGPURenderPipelineDescriptor extends IDLBase {

    private WGPUVertexState WGPUVertexState_TEMP_GEN_0;

    private WGPUPrimitiveState WGPUPrimitiveState_TEMP_GEN_0;

    private WGPUMultisampleState WGPUMultisampleState_TEMP_GEN_0;

    static private WGPURenderPipelineDescriptor WGPURenderPipelineDescriptor_TEMP_STATIC_GEN_0;

    static public final WGPURenderPipelineDescriptor NULL = WGPURenderPipelineDescriptor.native_new();

    public WGPURenderPipelineDescriptor() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    /*[-FFM;-NATIVE]
return (int64_t)new JGPU::WGPURenderPipelineDescriptor();
*/
    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPURenderPipelineDescriptor(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPURenderPipelineDescriptor native_new() {
        return new WGPURenderPipelineDescriptor((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPURenderPipelineDescriptor* nativeObject = (JGPU::WGPURenderPipelineDescriptor*)this_addr;
delete nativeObject;
*/
    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void setLabel(String value) {
        internal_native_SetLabel(native_address, value);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPURenderPipelineDescriptor* nativeObject = (JGPU::WGPURenderPipelineDescriptor*)this_addr;
nativeObject->SetLabel(value);
*/
    public static void internal_native_SetLabel(long this_addr, String value) {
        try {
            FFMHandles.internal_native_SetLabel__JLjava_lang_String_2.invokeExact(this_addr, (java.lang.foreign.MemorySegment) (value != null ? java.lang.foreign.Arena.global().allocateFrom(value) : java.lang.foreign.MemorySegment.NULL));
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void setNextInChain(WGPUChainedStruct chainedStruct) {
        internal_native_SetNextInChain(native_address, chainedStruct.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPURenderPipelineDescriptor* nativeObject = (JGPU::WGPURenderPipelineDescriptor*)this_addr;
nativeObject->SetNextInChain((JGPU::WGPUChainedStruct* )chainedStruct_addr);
*/
    public static void internal_native_SetNextInChain(long this_addr, long chainedStruct_addr) {
        try {
            FFMHandles.internal_native_SetNextInChain__JJ.invokeExact(this_addr, chainedStruct_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public WGPUVertexState getVertex() {
        long addr = internal_native_GetVertex_addr(native_address);
        if (addr == 0)
            return WGPUVertexState.NULL;
        if (WGPUVertexState_TEMP_GEN_0 == null)
            WGPUVertexState_TEMP_GEN_0 = WGPUVertexState.native_new();
        WGPUVertexState_TEMP_GEN_0.internal_reset(addr, false);
        return WGPUVertexState_TEMP_GEN_0;
    }

    /*[-FFM;-NATIVE]
JGPU::WGPURenderPipelineDescriptor* nativeObject = (JGPU::WGPURenderPipelineDescriptor*)this_addr;
static JGPU::WGPUVertexState copy_addr;
copy_addr = nativeObject->GetVertex();
return (int64_t)&copy_addr;*/
    public static long internal_native_GetVertex_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetVertex_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public WGPUPrimitiveState getPrimitive() {
        long addr = internal_native_GetPrimitive_addr(native_address);
        if (addr == 0)
            return WGPUPrimitiveState.NULL;
        if (WGPUPrimitiveState_TEMP_GEN_0 == null)
            WGPUPrimitiveState_TEMP_GEN_0 = WGPUPrimitiveState.native_new();
        WGPUPrimitiveState_TEMP_GEN_0.internal_reset(addr, false);
        return WGPUPrimitiveState_TEMP_GEN_0;
    }

    /*[-FFM;-NATIVE]
JGPU::WGPURenderPipelineDescriptor* nativeObject = (JGPU::WGPURenderPipelineDescriptor*)this_addr;
static JGPU::WGPUPrimitiveState copy_addr;
copy_addr = nativeObject->GetPrimitive();
return (int64_t)&copy_addr;*/
    public static long internal_native_GetPrimitive_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetPrimitive_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void setFragment(WGPUFragmentState fragmentState) {
        internal_native_SetFragment(native_address, fragmentState.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPURenderPipelineDescriptor* nativeObject = (JGPU::WGPURenderPipelineDescriptor*)this_addr;
nativeObject->SetFragment((JGPU::WGPUFragmentState* )fragmentState_addr);
*/
    public static void internal_native_SetFragment(long this_addr, long fragmentState_addr) {
        try {
            FFMHandles.internal_native_SetFragment__JJ.invokeExact(this_addr, fragmentState_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void setDepthStencil(WGPUDepthStencilState depthStencilState) {
        internal_native_SetDepthStencil(native_address, depthStencilState.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPURenderPipelineDescriptor* nativeObject = (JGPU::WGPURenderPipelineDescriptor*)this_addr;
nativeObject->SetDepthStencil((JGPU::WGPUDepthStencilState* )depthStencilState_addr);
*/
    public static void internal_native_SetDepthStencil(long this_addr, long depthStencilState_addr) {
        try {
            FFMHandles.internal_native_SetDepthStencil__JJ.invokeExact(this_addr, depthStencilState_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public WGPUMultisampleState getMultisample() {
        long addr = internal_native_GetMultisample_addr(native_address);
        if (addr == 0)
            return WGPUMultisampleState.NULL;
        if (WGPUMultisampleState_TEMP_GEN_0 == null)
            WGPUMultisampleState_TEMP_GEN_0 = WGPUMultisampleState.native_new();
        WGPUMultisampleState_TEMP_GEN_0.internal_reset(addr, false);
        return WGPUMultisampleState_TEMP_GEN_0;
    }

    /*[-FFM;-NATIVE]
JGPU::WGPURenderPipelineDescriptor* nativeObject = (JGPU::WGPURenderPipelineDescriptor*)this_addr;
static JGPU::WGPUMultisampleState copy_addr;
copy_addr = nativeObject->GetMultisample();
return (int64_t)&copy_addr;*/
    public static long internal_native_GetMultisample_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetMultisample_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public void setLayout(WGPUPipelineLayout pipelineLayout) {
        internal_native_SetLayout(native_address, pipelineLayout.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPURenderPipelineDescriptor* nativeObject = (JGPU::WGPURenderPipelineDescriptor*)this_addr;
nativeObject->SetLayout((JGPU::WGPUPipelineLayout* )pipelineLayout_addr);
*/
    public static void internal_native_SetLayout(long this_addr, long pipelineLayout_addr) {
        try {
            FFMHandles.internal_native_SetLayout__JJ.invokeExact(this_addr, pipelineLayout_addr);
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    public static WGPURenderPipelineDescriptor obtain() {
        long addr = internal_native_Obtain_addr();
        if (addr == 0)
            return WGPURenderPipelineDescriptor.NULL;
        if (WGPURenderPipelineDescriptor_TEMP_STATIC_GEN_0 == null)
            WGPURenderPipelineDescriptor_TEMP_STATIC_GEN_0 = WGPURenderPipelineDescriptor.native_new();
        WGPURenderPipelineDescriptor_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return WGPURenderPipelineDescriptor_TEMP_STATIC_GEN_0;
    }

    /*[-FFM;-NATIVE]
return (int64_t)JGPU::WGPURenderPipelineDescriptor::Obtain();
*/
    public static long internal_native_Obtain_addr() {
        try {
            return (long) FFMHandles.internal_native_Obtain_addr__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP;

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static {
            LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();
        }

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPURenderPipelineDescriptor_internal_1native_1create_1addr__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPURenderPipelineDescriptor_internal_1native_1deleteNative__J").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLabel__JLjava_lang_String_2 = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPURenderPipelineDescriptor_internal_1native_1SetLabel__JLjava_lang_String_2").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));

        static final java.lang.invoke.MethodHandle internal_native_SetNextInChain__JJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPURenderPipelineDescriptor_internal_1native_1SetNextInChain__JJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetVertex_addr__J = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPURenderPipelineDescriptor_internal_1native_1GetVertex_1addr__J").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetPrimitive_addr__J = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPURenderPipelineDescriptor_internal_1native_1GetPrimitive_1addr__J").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetFragment__JJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPURenderPipelineDescriptor_internal_1native_1SetFragment__JJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDepthStencil__JJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPURenderPipelineDescriptor_internal_1native_1SetDepthStencil__JJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetMultisample_addr__J = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPURenderPipelineDescriptor_internal_1native_1GetMultisample_1addr__J").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLayout__JJ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPURenderPipelineDescriptor_internal_1native_1SetLayout__JJ").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Obtain_addr__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPURenderPipelineDescriptor_internal_1native_1Obtain_1addr__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_LONG));
    }
}
