/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class WGPUSupportedFeatures extends NativeObject {

    static private WGPUSupportedFeatures WGPUSupportedFeatures_TEMP_STATIC_GEN_0;

    static public final WGPUSupportedFeatures NULL = WGPUSupportedFeatures.native_new();

    public WGPUSupportedFeatures() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUSupportedFeatures(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUSupportedFeatures native_new() {
        return new WGPUSupportedFeatures((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int getFeatureCount() {
        return internal_native_GetFeatureCount(native_address);
    }

    public static int internal_native_GetFeatureCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetFeatureCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public WGPUFeatureName getFeatureAt(int index) {
        int value = internal_native_GetFeatureAt(native_address, index);
        WGPUFeatureName[] values = WGPUFeatureName.values();
        for (int i = 0; i < values.length; i++) {
            WGPUFeatureName enumVal = values[i];
            if (enumVal != WGPUFeatureName.CUSTOM && enumVal.getValue() == value)
                return enumVal;
        }
        return WGPUFeatureName.CUSTOM.setValue(value);
    }

    public static int internal_native_GetFeatureAt(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_GetFeatureAt__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static WGPUSupportedFeatures obtain() {
        long addr = internal_native_Obtain_addr();
        if (addr == 0)
            return WGPUSupportedFeatures.NULL;
        if (WGPUSupportedFeatures_TEMP_STATIC_GEN_0 == null)
            WGPUSupportedFeatures_TEMP_STATIC_GEN_0 = WGPUSupportedFeatures.native_new();
        WGPUSupportedFeatures_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return WGPUSupportedFeatures_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_Obtain_addr() {
        try {
            return (long) FFMHandles.internal_native_Obtain_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpusupportedfeatures_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpusupportedfeatures_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetFeatureCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpusupportedfeatures_getfeaturecount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetFeatureAt__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_webgpu_wgpusupportedfeatures_getfeatureat", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_Obtain_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_webgpu_wgpusupportedfeatures_obtain_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));
    }
}
