/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUBufferUsage implements NativeEnum<WGPUBufferUsage> {

    CUSTOM(0),
    None(WGPUBufferUsage_None_NATIVE()),
    MapRead(WGPUBufferUsage_MapRead_NATIVE()),
    MapWrite(WGPUBufferUsage_MapWrite_NATIVE()),
    CopySrc(WGPUBufferUsage_CopySrc_NATIVE()),
    CopyDst(WGPUBufferUsage_CopyDst_NATIVE()),
    Index(WGPUBufferUsage_Index_NATIVE()),
    Vertex(WGPUBufferUsage_Vertex_NATIVE()),
    Uniform(WGPUBufferUsage_Uniform_NATIVE()),
    Storage(WGPUBufferUsage_Storage_NATIVE()),
    Indirect(WGPUBufferUsage_Indirect_NATIVE()),
    QueryResolve(WGPUBufferUsage_QueryResolve_NATIVE());

    private int value;

    private WGPUBufferUsage(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUBufferUsage setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUBufferUsage getCustom() {
        return CUSTOM;
    }

    private static int WGPUBufferUsage_None_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3399882394", "WGPUBufferUsage.WGPUBufferUsage_None_NATIVE");
            return (int) FFMHandles.WGPUBufferUsage_None_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUBufferUsage_MapRead_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1291391548", "WGPUBufferUsage.WGPUBufferUsage_MapRead_NATIVE");
            return (int) FFMHandles.WGPUBufferUsage_MapRead_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUBufferUsage_MapWrite_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n971192901", "WGPUBufferUsage.WGPUBufferUsage_MapWrite_NATIVE");
            return (int) FFMHandles.WGPUBufferUsage_MapWrite_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUBufferUsage_CopySrc_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2099226201", "WGPUBufferUsage.WGPUBufferUsage_CopySrc_NATIVE");
            return (int) FFMHandles.WGPUBufferUsage_CopySrc_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUBufferUsage_CopyDst_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2425224506", "WGPUBufferUsage.WGPUBufferUsage_CopyDst_NATIVE");
            return (int) FFMHandles.WGPUBufferUsage_CopyDst_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUBufferUsage_Index_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n4184477436", "WGPUBufferUsage.WGPUBufferUsage_Index_NATIVE");
            return (int) FFMHandles.WGPUBufferUsage_Index_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUBufferUsage_Vertex_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1034356230", "WGPUBufferUsage.WGPUBufferUsage_Vertex_NATIVE");
            return (int) FFMHandles.WGPUBufferUsage_Vertex_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUBufferUsage_Uniform_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n3902457054", "WGPUBufferUsage.WGPUBufferUsage_Uniform_NATIVE");
            return (int) FFMHandles.WGPUBufferUsage_Uniform_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUBufferUsage_Storage_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n766473893", "WGPUBufferUsage.WGPUBufferUsage_Storage_NATIVE");
            return (int) FFMHandles.WGPUBufferUsage_Storage_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUBufferUsage_Indirect_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2518703280", "WGPUBufferUsage.WGPUBufferUsage_Indirect_NATIVE");
            return (int) FFMHandles.WGPUBufferUsage_Indirect_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUBufferUsage_QueryResolve_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n56348518", "WGPUBufferUsage.WGPUBufferUsage_QueryResolve_NATIVE");
            return (int) FFMHandles.WGPUBufferUsage_QueryResolve_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle WGPUBufferUsage_None_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3399882394", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBufferUsage_MapRead_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1291391548", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBufferUsage_MapWrite_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n971192901", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBufferUsage_CopySrc_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2099226201", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBufferUsage_CopyDst_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2425224506", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBufferUsage_Index_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n4184477436", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBufferUsage_Vertex_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1034356230", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBufferUsage_Uniform_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n3902457054", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBufferUsage_Storage_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n766473893", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBufferUsage_Indirect_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2518703280", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBufferUsage_QueryResolve_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n56348518", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
