/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUPowerPreference implements NativeEnum<WGPUPowerPreference> {

    CUSTOM(0), Undefined(WGPUPowerPreference_Undefined_NATIVE()), LowPower(WGPUPowerPreference_LowPower_NATIVE()), HighPerformance(WGPUPowerPreference_HighPerformance_NATIVE()), Force32(WGPUPowerPreference_Force32_NATIVE());

    private int value;

    private WGPUPowerPreference(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUPowerPreference setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUPowerPreference getCustom() {
        return CUSTOM;
    }

    private static int WGPUPowerPreference_Undefined_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n1557270904", "WGPUPowerPreference.WGPUPowerPreference_Undefined_NATIVE");
            return (int) FFMHandles.WGPUPowerPreference_Undefined_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUPowerPreference_LowPower_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n162023605", "WGPUPowerPreference.WGPUPowerPreference_LowPower_NATIVE");
            return (int) FFMHandles.WGPUPowerPreference_LowPower_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUPowerPreference_HighPerformance_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n2145300950", "WGPUPowerPreference.WGPUPowerPreference_HighPerformance_NATIVE");
            return (int) FFMHandles.WGPUPowerPreference_HighPerformance_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUPowerPreference_Force32_NATIVE() {
        try {
            com.github.xpenatan.jparser.runtime.helper.FFMCriticalCrashTrace.mark("n146897202", "WGPUPowerPreference.WGPUPowerPreference_Force32_NATIVE");
            return (int) FFMHandles.WGPUPowerPreference_Force32_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle WGPUPowerPreference_Undefined_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n1557270904", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUPowerPreference_LowPower_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n162023605", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUPowerPreference_HighPerformance_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n2145300950", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUPowerPreference_Force32_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("n146897202", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
