/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUMapMode implements NativeEnum<WGPUMapMode> {

    CUSTOM(0), None(WGPUMapMode_None_NATIVE()), Read(WGPUMapMode_Read_NATIVE()), Write(WGPUMapMode_Write_NATIVE());

    private int value;

    private WGPUMapMode(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUMapMode setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUMapMode getCustom() {
        return CUSTOM;
    }

    private static int WGPUMapMode_None_NATIVE() {
        try {
            return (int) FFMHandles.WGPUMapMode_None_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUMapMode_Read_NATIVE() {
        try {
            return (int) FFMHandles.WGPUMapMode_Read_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static int WGPUMapMode_Write_NATIVE() {
        try {
            return (int) FFMHandles.WGPUMapMode_Write_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle WGPUMapMode_None_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUMapMode_WGPUMapMode_1None_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUMapMode_Read_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUMapMode_WGPUMapMode_1Read_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUMapMode_Write_NATIVE__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUMapMode_WGPUMapMode_1Write_1NATIVE__", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
