/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class WGPUMultisampleState extends NativeObject {

    static public final WGPUMultisampleState NULL = WGPUMultisampleState.native_new();

    public WGPUMultisampleState() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    /*[-FFM;-NATIVE]
return (int64_t)new JGPU::WGPUMultisampleState();
*/
    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUMultisampleState(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUMultisampleState native_new() {
        return new WGPUMultisampleState((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUMultisampleState* nativeObject = (JGPU::WGPUMultisampleState*)this_addr;
delete nativeObject;
*/
    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void setNextInChain(WGPUChainedStruct chainedStruct) {
        internal_native_SetNextInChain(native_address, chainedStruct.native_address);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUMultisampleState* nativeObject = (JGPU::WGPUMultisampleState*)this_addr;
nativeObject->SetNextInChain((JGPU::WGPUChainedStruct* )chainedStruct_addr);
*/
    public static void internal_native_SetNextInChain(long this_addr, long chainedStruct_addr) {
        try {
            FFMHandles.internal_native_SetNextInChain__JJ.invokeExact(this_addr, chainedStruct_addr);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void setCount(int count) {
        internal_native_SetCount(native_address, count);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUMultisampleState* nativeObject = (JGPU::WGPUMultisampleState*)this_addr;
nativeObject->SetCount((int)count);
*/
    public static void internal_native_SetCount(long this_addr, int count) {
        try {
            FFMHandles.internal_native_SetCount__JI.invokeExact(this_addr, count);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void setMask(int mask) {
        internal_native_SetMask(native_address, mask);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUMultisampleState* nativeObject = (JGPU::WGPUMultisampleState*)this_addr;
nativeObject->SetMask((int)mask);
*/
    public static void internal_native_SetMask(long this_addr, int mask) {
        try {
            FFMHandles.internal_native_SetMask__JI.invokeExact(this_addr, mask);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    public void setAlphaToCoverageEnabled(boolean alphaToCoverageEnabled) {
        internal_native_SetAlphaToCoverageEnabled(native_address, alphaToCoverageEnabled);
    }

    /*[-FFM;-NATIVE]
JGPU::WGPUMultisampleState* nativeObject = (JGPU::WGPUMultisampleState*)this_addr;
nativeObject->SetAlphaToCoverageEnabled(alphaToCoverageEnabled);
*/
    public static void internal_native_SetAlphaToCoverageEnabled(long this_addr, boolean alphaToCoverageEnabled) {
        try {
            FFMHandles.internal_native_SetAlphaToCoverageEnabled__JZ.invokeExact(this_addr, alphaToCoverageEnabled);
        } catch (Throwable e) {
            throw FFMHandles.rethrow(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_CRITICAL = new java.lang.foreign.Linker.Option[] { java.lang.foreign.Linker.Option.critical(true) };

        private static final java.lang.foreign.Linker.Option[] LINKER_OPTIONS_DEFAULT = new java.lang.foreign.Linker.Option[0];

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static RuntimeException rethrow(Throwable e) {
            if (e instanceof RuntimeException)
                return (RuntimeException) e;
            if (e instanceof Error)
                throw (Error) e;
            return new RuntimeException(e);
        }

        static java.lang.invoke.MethodHandle downcallDefault(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
        }

        static java.lang.invoke.MethodHandle downcallCritical(String symbolName, java.lang.foreign.FunctionDescriptor descriptor) {
            java.lang.foreign.MemorySegment symbol = LOOKUP.find(symbolName).orElseThrow();
            try {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_CRITICAL);
            } catch (Throwable ignored) {
                return LINKER.downcallHandle(symbol, descriptor, LINKER_OPTIONS_DEFAULT);
            }
        }

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUMultisampleState_internal_1native_1create_1addr__", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUMultisampleState_internal_1native_1deleteNative__J", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetNextInChain__JJ = downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUMultisampleState_internal_1native_1SetNextInChain__JJ", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetCount__JI = downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUMultisampleState_internal_1native_1SetCount__JI", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_SetMask__JI = downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUMultisampleState_internal_1native_1SetMask__JI", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_SetAlphaToCoverageEnabled__JZ = downcallDefault("jparser_com_github_xpenatan_webgpu_WGPUMultisampleState_internal_1native_1SetAlphaToCoverageEnabled__JZ", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));
    }
}
