/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLEnum;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public enum WGPUBlendOperation implements IDLEnum<WGPUBlendOperation> {

    CUSTOM(0),
    Undefined(WGPUBlendOperation_Undefined_NATIVE()),
    Add(WGPUBlendOperation_Add_NATIVE()),
    Subtract(WGPUBlendOperation_Subtract_NATIVE()),
    ReverseSubtract(WGPUBlendOperation_ReverseSubtract_NATIVE()),
    Min(WGPUBlendOperation_Min_NATIVE()),
    Max(WGPUBlendOperation_Max_NATIVE()),
    Force32(WGPUBlendOperation_Force32_NATIVE());

    private int value;

    private WGPUBlendOperation(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUBlendOperation setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUBlendOperation getCustom() {
        return CUSTOM;
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUBlendOperation_Undefined;
*/
    private static int WGPUBlendOperation_Undefined_NATIVE() {
        try {
            return (int) FFMHandles.WGPUBlendOperation_Undefined_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUBlendOperation_Add;
*/
    private static int WGPUBlendOperation_Add_NATIVE() {
        try {
            return (int) FFMHandles.WGPUBlendOperation_Add_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUBlendOperation_Subtract;
*/
    private static int WGPUBlendOperation_Subtract_NATIVE() {
        try {
            return (int) FFMHandles.WGPUBlendOperation_Subtract_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUBlendOperation_ReverseSubtract;
*/
    private static int WGPUBlendOperation_ReverseSubtract_NATIVE() {
        try {
            return (int) FFMHandles.WGPUBlendOperation_ReverseSubtract_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUBlendOperation_Min;
*/
    private static int WGPUBlendOperation_Min_NATIVE() {
        try {
            return (int) FFMHandles.WGPUBlendOperation_Min_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUBlendOperation_Max;
*/
    private static int WGPUBlendOperation_Max_NATIVE() {
        try {
            return (int) FFMHandles.WGPUBlendOperation_Max_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    /*[-FFM;-NATIVE]
return (int64_t)WGPUBlendOperation_Force32;
*/
    private static int WGPUBlendOperation_Force32_NATIVE() {
        try {
            return (int) FFMHandles.WGPUBlendOperation_Force32_NATIVE__.invokeExact();
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    private static final class FFMHandles {

        private static final java.lang.foreign.SymbolLookup LOOKUP;

        private static final java.lang.foreign.Linker LINKER = java.lang.foreign.Linker.nativeLinker();

        static {
            LOOKUP = java.lang.foreign.SymbolLookup.loaderLookup();
        }

        static final java.lang.invoke.MethodHandle WGPUBlendOperation_Undefined_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUBlendOperation_WGPUBlendOperation_1Undefined_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBlendOperation_Add_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUBlendOperation_WGPUBlendOperation_1Add_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBlendOperation_Subtract_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUBlendOperation_WGPUBlendOperation_1Subtract_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBlendOperation_ReverseSubtract_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUBlendOperation_WGPUBlendOperation_1ReverseSubtract_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBlendOperation_Min_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUBlendOperation_WGPUBlendOperation_1Min_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBlendOperation_Max_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUBlendOperation_WGPUBlendOperation_1Max_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle WGPUBlendOperation_Force32_NATIVE__ = LINKER.downcallHandle(LOOKUP.find("jparser_com_github_xpenatan_webgpu_WGPUBlendOperation_WGPUBlendOperation_1Force32_1NATIVE__").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));
    }
}
