/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package n;

import com.github.xpenatan.webgpu.*;

final public class n1210092402 {

    public static native void n1950147494(long this_addr);

    public static native void n4048457511(long this_addr, String label);

    public static native void n189091175(long this_addr, long chainedStruct_addr);
}
