/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package n;

import com.github.xpenatan.webgpu.*;

final public class n1493374126 {

    public static native long n1630520540();

    public static native void n3859422690(long this_addr);

    public static native void n718953323(long this_addr, String value);

    public static native void n3318306731(long this_addr, long chainedStruct_addr);

    public static native long n784102885();
}
