/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package n;

import com.github.xpenatan.webgpu.*;

final public class n1770153308 {

    public static native long n3759086318();

    public static native void n3121070864(long this_addr);

    public static native void n752216251(long this_addr, long texture_addr);

    public static native int n134036214(long this_addr);

    public static native long n2912668663();
}
