/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package n;

import com.github.xpenatan.webgpu.*;

final public class n2048309877 {

    static native public int n3007256461();

    static native public int n2680167321();

    static native public int n433644308();
}
