/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package n;

import com.github.xpenatan.webgpu.*;

final public class n2217034401 {

    public static native void n2183073557(long this_addr);

    public static native long n2796164933(long this_addr);

    public static native void n664329657(long this_addr, int value);

    public static native void n2986654491(long this_addr, int index, int value);

    public static native int n1305951430(long this_addr, int index);

    public static native int n200695299(long this_addr);

    public static native int n1594238627(long this_addr);

    public static native int n1761485417(long this_addr);

    public static native void n2232014124(long this_addr);

    public static native void n2267127233(long this_addr, int newLimit);

    public static native int n617877522(long this_addr);

    public static native void n1137537201(long this_addr, int newPosition);

    public static native int n261950298(long this_addr);

    public static native void n1547344426(long this_addr);
}
