/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package n;

import com.github.xpenatan.webgpu.*;

final public class n266518020 {

    public static native void n3364876728(long this_addr);

    public static native void n1229417231(long this_addr);

    public static native void n976554704(long this_addr, long descriptor_addr, long valueOut_addr);

    public static native void n2035541062(long this_addr, long descriptor_addr, long valueOut_addr);

    public static native long n1881626826(long this_addr, long descriptor_addr);

    public static native void n65445665(long this_addr, long descriptor_addr, long valueOut_addr);

    public static native void n1019050349(long this_addr, long descriptor_addr, long valueOut_addr);

    public static native void n976022201(long this_addr, long descriptor_addr, long valueOut_addr);

    public static native void n2480616178(long this_addr, long descriptor_addr, long valueOut_addr);

    public static native void n623129508(long this_addr, long descriptor_addr, long valueOut_addr);

    public static native void n1766028814(long this_addr, long descriptor_addr, long valueOut_addr);

    public static native void n1082446726(long this_addr, long descriptor_addr, long valueOut_addr);

    public static native void n2420806858(long this_addr, long descriptor_addr, long valueOut_addr);

    public static native void n392988557(long this_addr, long descriptor_addr, long shaderModule_addr);

    public static native void n19584855(long this_addr, long descriptor_addr, long valueOut_addr);

    public static native void n1880158972(long this_addr);

    public static native void n216365221(long this_addr, long features_addr);

    public static native boolean n376083009(long this_addr, int feature);

    public static native void n3799845056(long this_addr, long limits_addr);

    public static native long n784176897(long this_addr);
}
