/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package n;

import com.github.xpenatan.webgpu.*;

final public class n3410848009 {

    public static native long n2966876769();

    public static native void n4090207101(long this_addr);

    public static native void n4069667824(long this_addr, String value);

    public static native void n3307693488(long this_addr, long chainedStruct_addr);

    public static native void n2041305073(long this_addr, long timestampWrites_addr);

    public static native long n2120459114();
}
