/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package n;

import com.github.xpenatan.webgpu.*;

final public class n4291460093 {

    public static native long n2451485677();

    public static native void n219869553(long this_addr);

    public static native void n1240836476(long this_addr, String label);

    public static native void n3110583222(long this_addr);

    public static native boolean n2906849707(long this_addr);

    public static native long n1605068022();
}
