/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.webgpu;

import com.github.xpenatan.webgpu.idl.IDLBase;

public class WGPUQuerySetDescriptor extends IDLBase {

    static private WGPUQuerySetDescriptor WGPUQuerySetDescriptor_TEMP_STATIC_GEN_0;

    static public final WGPUQuerySetDescriptor NULL = WGPUQuerySetDescriptor.native_new();

    public WGPUQuerySetDescriptor() {
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*[-JNI;-NATIVE]
return (jlong)new JGPU::WGPUQuerySetDescriptor();
*/
    public static native long internal_native_create();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUQuerySetDescriptor(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUQuerySetDescriptor native_new() {
        return new WGPUQuerySetDescriptor((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
JGPU::WGPUQuerySetDescriptor* nativeObject = (JGPU::WGPUQuerySetDescriptor*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public void setLabel(String label) {
        internal_native_SetLabel(native_address, label);
    }

    /*[-JNI;-NATIVE]
JGPU::WGPUQuerySetDescriptor* nativeObject = (JGPU::WGPUQuerySetDescriptor*)this_addr;
nativeObject->SetLabel(label);
*/
    public static native void internal_native_SetLabel(long this_addr, String label);

    public void setNextInChain(WGPUChainedStruct chainedStruct) {
        internal_native_SetNextInChain(native_address, chainedStruct.native_address);
    }

    /*[-JNI;-NATIVE]
JGPU::WGPUQuerySetDescriptor* nativeObject = (JGPU::WGPUQuerySetDescriptor*)this_addr;
nativeObject->SetNextInChain((JGPU::WGPUChainedStruct* )chainedStruct_addr);
*/
    public static native void internal_native_SetNextInChain(long this_addr, long chainedStruct_addr);

    public void setType(WGPUQueryType type) {
        internal_native_SetType(native_address, type.getValue());
    }

    /*[-JNI;-NATIVE]
JGPU::WGPUQuerySetDescriptor* nativeObject = (JGPU::WGPUQuerySetDescriptor*)this_addr;
nativeObject->SetType((::WGPUQueryType)type);
*/
    public static native void internal_native_SetType(long this_addr, long type);

    public void setCount(int count) {
        internal_native_SetCount(native_address, count);
    }

    /*[-JNI;-NATIVE]
JGPU::WGPUQuerySetDescriptor* nativeObject = (JGPU::WGPUQuerySetDescriptor*)this_addr;
nativeObject->SetCount((int)count);
*/
    public static native void internal_native_SetCount(long this_addr, int count);

    public static WGPUQuerySetDescriptor obtain() {
        long pointer = internal_native_Obtain();
        if (pointer == 0)
            return WGPUQuerySetDescriptor.NULL;
        if (WGPUQuerySetDescriptor_TEMP_STATIC_GEN_0 == null)
            WGPUQuerySetDescriptor_TEMP_STATIC_GEN_0 = WGPUQuerySetDescriptor.native_new();
        WGPUQuerySetDescriptor_TEMP_STATIC_GEN_0.internal_reset(pointer, false);
        return WGPUQuerySetDescriptor_TEMP_STATIC_GEN_0;
    }

    /*[-JNI;-NATIVE]
return (jlong)JGPU::WGPUQuerySetDescriptor::Obtain();
*/
    public static native long internal_native_Obtain();
}
