/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLEnum;

public enum WGPUTextureDimension implements IDLEnum<WGPUTextureDimension> {

    CUSTOM(0),
    Undefined(WGPUTextureDimension_Undefined_NATIVE()),
    _1D(WGPUTextureDimension_1D_NATIVE()),
    _2D(WGPUTextureDimension_2D_NATIVE()),
    _3D(WGPUTextureDimension_3D_NATIVE()),
    Force32(WGPUTextureDimension_Force32_NATIVE());

    private int value;

    private WGPUTextureDimension(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUTextureDimension setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUTextureDimension getCustom() {
        return CUSTOM;
    }

    private static native int WGPUTextureDimension_Undefined_NATIVE();

    private static native int WGPUTextureDimension_1D_NATIVE();

    private static native int WGPUTextureDimension_2D_NATIVE();

    private static native int WGPUTextureDimension_3D_NATIVE();

    private static native int WGPUTextureDimension_Force32_NATIVE();
}
