/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;

public class WGPUSupportedWGSLLanguageFeatures extends IDLBase {

    static public final WGPUSupportedWGSLLanguageFeatures NULL = WGPUSupportedWGSLLanguageFeatures.native_new();

    public WGPUSupportedWGSLLanguageFeatures() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUSupportedWGSLLanguageFeatures(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUSupportedWGSLLanguageFeatures native_new() {
        return new WGPUSupportedWGSLLanguageFeatures((byte) 0, (char) 0);
    }

    public int getFeatureCount() {
        return 0;
    }

    public WGPUWGSLLanguageFeatureName getFeatureAt(int index) {
        return null;
    }

    public static WGPUSupportedWGSLLanguageFeatures obtain() {
        return null;
    }
}
