/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;

public class WGPUShaderSourceSPIRV extends IDLBase {

    static public final WGPUShaderSourceSPIRV NULL = WGPUShaderSourceSPIRV.native_new();

    public WGPUShaderSourceSPIRV() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUShaderSourceSPIRV(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUShaderSourceSPIRV native_new() {
        return new WGPUShaderSourceSPIRV((byte) 0, (char) 0);
    }

    public static WGPUShaderSourceSPIRV obtain() {
        return null;
    }
}
