/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;

public class WGPUInstance extends IDLBase {

    static public final WGPUInstance NULL = WGPUInstance.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUInstance(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUInstance native_new() {
        return new WGPUInstance((byte) 0, (char) 0);
    }

    public boolean isValid() {
        return false;
    }

    public void release() {
    }

    public void requestAdapter(WGPURequestAdapterOptions options, WGPUCallbackMode mode, WGPURequestAdapterCallback callback) {
    }

    public WGPUSurface createWebSurface(String canvas) {
        return null;
    }

    public WGPUSurface createWindowsSurface(IDLBase hwnd) {
        return null;
    }

    public WGPUSurface createLinuxSurface(boolean isWayland, IDLBase windowOrSurface, IDLBase display) {
        return null;
    }

    public WGPUSurface createMacSurface(IDLBase metalLayer) {
        return null;
    }

    public WGPUSurface createAndroidSurface(WGPUAndroidWindow surface) {
        return null;
    }

    public void processEvents() {
    }

    public WGPUWaitStatus waitAny(WGPUVectorFutureWaitInfo futureVector, int timeoutNS) {
        return null;
    }
}
