/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;

public class WGPUVectorFutureWaitInfo extends IDLBase {

    static public final WGPUVectorFutureWaitInfo NULL = WGPUVectorFutureWaitInfo.native_new();

    public WGPUVectorFutureWaitInfo() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUVectorFutureWaitInfo(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUVectorFutureWaitInfo native_new() {
        return new WGPUVectorFutureWaitInfo((byte) 0, (char) 0);
    }

    public int size() {
        return 0;
    }

    public void clear() {
    }

    public void push_back(WGPUFutureWaitInfo entry) {
    }

    public static WGPUVectorFutureWaitInfo obtain() {
        return null;
    }
}
