/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLEnum;

public enum WGPUBlendFactor implements IDLEnum<WGPUBlendFactor> {

    CUSTOM(0),
    Undefined(WGPUBlendFactor_Undefined_NATIVE()),
    Zero(WGPUBlendFactor_Zero_NATIVE()),
    One(WGPUBlendFactor_One_NATIVE()),
    Src(WGPUBlendFactor_Src_NATIVE()),
    OneMinusSrc(WGPUBlendFactor_OneMinusSrc_NATIVE()),
    SrcAlpha(WGPUBlendFactor_SrcAlpha_NATIVE()),
    OneMinusSrcAlpha(WGPUBlendFactor_OneMinusSrcAlpha_NATIVE()),
    Dst(WGPUBlendFactor_Dst_NATIVE()),
    OneMinusDst(WGPUBlendFactor_OneMinusDst_NATIVE()),
    DstAlpha(WGPUBlendFactor_DstAlpha_NATIVE()),
    OneMinusDstAlpha(WGPUBlendFactor_OneMinusDstAlpha_NATIVE()),
    SrcAlphaSaturated(WGPUBlendFactor_SrcAlphaSaturated_NATIVE()),
    Constant(WGPUBlendFactor_Constant_NATIVE()),
    OneMinusConstant(WGPUBlendFactor_OneMinusConstant_NATIVE()),
    Src1(WGPUBlendFactor_Src1_NATIVE()),
    OneMinusSrc1(WGPUBlendFactor_OneMinusSrc1_NATIVE()),
    Src1Alpha(WGPUBlendFactor_Src1Alpha_NATIVE()),
    OneMinusSrc1Alpha(WGPUBlendFactor_OneMinusSrc1Alpha_NATIVE()),
    Force32(WGPUBlendFactor_Force32_NATIVE());

    private int value;

    private WGPUBlendFactor(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUBlendFactor setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUBlendFactor getCustom() {
        return CUSTOM;
    }

    private static native int WGPUBlendFactor_Undefined_NATIVE();

    private static native int WGPUBlendFactor_Zero_NATIVE();

    private static native int WGPUBlendFactor_One_NATIVE();

    private static native int WGPUBlendFactor_Src_NATIVE();

    private static native int WGPUBlendFactor_OneMinusSrc_NATIVE();

    private static native int WGPUBlendFactor_SrcAlpha_NATIVE();

    private static native int WGPUBlendFactor_OneMinusSrcAlpha_NATIVE();

    private static native int WGPUBlendFactor_Dst_NATIVE();

    private static native int WGPUBlendFactor_OneMinusDst_NATIVE();

    private static native int WGPUBlendFactor_DstAlpha_NATIVE();

    private static native int WGPUBlendFactor_OneMinusDstAlpha_NATIVE();

    private static native int WGPUBlendFactor_SrcAlphaSaturated_NATIVE();

    private static native int WGPUBlendFactor_Constant_NATIVE();

    private static native int WGPUBlendFactor_OneMinusConstant_NATIVE();

    private static native int WGPUBlendFactor_Src1_NATIVE();

    private static native int WGPUBlendFactor_OneMinusSrc1_NATIVE();

    private static native int WGPUBlendFactor_Src1Alpha_NATIVE();

    private static native int WGPUBlendFactor_OneMinusSrc1Alpha_NATIVE();

    private static native int WGPUBlendFactor_Force32_NATIVE();
}
