/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.webgpu;

import java.util.Map;
import java.util.HashMap;
import com.github.xpenatan.webgpu.idl.IDLEnum;

public enum WGPURequestDeviceStatus implements IDLEnum<WGPURequestDeviceStatus> {

    CUSTOM(0), Success(WGPURequestDeviceStatus_Success_NATIVE()), Error(WGPURequestDeviceStatus_Error_NATIVE()), Force32(WGPURequestDeviceStatus_Force32_NATIVE());

    private int value;

    private WGPURequestDeviceStatus(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPURequestDeviceStatus setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPURequestDeviceStatus getCustom() {
        return CUSTOM;
    }

    public static final Map<Integer, WGPURequestDeviceStatus> MAP = new HashMap<>();

    static {
        for (WGPURequestDeviceStatus value : values()) {
            if (value != CUSTOM) {
                MAP.put(value.value, value);
            }
        }
    }

    /*[-JNI;-NATIVE]
return (jlong)WGPURequestDeviceStatus_Success;
*/
    private static native int WGPURequestDeviceStatus_Success_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPURequestDeviceStatus_Error;
*/
    private static native int WGPURequestDeviceStatus_Error_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPURequestDeviceStatus_Force32;
*/
    private static native int WGPURequestDeviceStatus_Force32_NATIVE();
}
