/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;

public class WGPUTexelCopyTextureInfo extends IDLBase {

    public final static WGPUTexelCopyTextureInfo NULL = native_new();

    public static WGPUTexelCopyTextureInfo native_new() {
        return new WGPUTexelCopyTextureInfo((byte) 0, (char) 0);
    }

    private WGPUTexelCopyTextureInfo(byte v, char c) {
    }

    public WGPUTexelCopyTextureInfo() {
    }

    public void setTexture(WGPUTexture texture) {
    }

    public void setMipLevel(int mipLevel) {
    }

    public WGPUOrigin3D getOrigin() {
        return null;
    }

    public void setAspect(WGPUTextureAspect aspect) {
    }

    public static WGPUTexelCopyTextureInfo obtain() {
        return null;
    }
}
