/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLEnum;

public enum WGPUOptionalBool implements IDLEnum<WGPUOptionalBool> {

    CUSTOM(0), False(WGPUOptionalBool_False_NATIVE()), True(WGPUOptionalBool_True_NATIVE()), Undefined(WGPUOptionalBool_Undefined_NATIVE()), Force32(WGPUOptionalBool_Force32_NATIVE());

    private int value;

    private WGPUOptionalBool(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUOptionalBool setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUOptionalBool getCustom() {
        return CUSTOM;
    }

    /*[-JNI;-NATIVE]
return (jlong)WGPUOptionalBool_False;
*/
    private static native int WGPUOptionalBool_False_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUOptionalBool_True;
*/
    private static native int WGPUOptionalBool_True_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUOptionalBool_Undefined;
*/
    private static native int WGPUOptionalBool_Undefined_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUOptionalBool_Force32;
*/
    private static native int WGPUOptionalBool_Force32_NATIVE();
}
