/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;

public class WGPUShaderModule extends IDLBase {

    static public final WGPUShaderModule NULL = WGPUShaderModule.native_new();

    public WGPUShaderModule() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUShaderModule(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUShaderModule native_new() {
        return new WGPUShaderModule((byte) 0, (char) 0);
    }

    public void setLabel(String label) {
    }

    public void release() {
    }

    public boolean isValid() {
        return false;
    }

    public void setCallback(WGPUCallbackMode callbackMode, WGPUCompilationInfoCallback callback) {
    }

    public static WGPUShaderModule obtain() {
        return null;
    }
}
