/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;

public class WGPURequestAdapterCallback extends IDLBase {

    static public final WGPURequestAdapterCallback NULL = WGPURequestAdapterCallback.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPURequestAdapterCallback(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPURequestAdapterCallback native_new() {
        return new WGPURequestAdapterCallback((byte) 0, (char) 0);
    }

    public WGPURequestAdapterCallback() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
    }

    protected void onCallback(WGPURequestAdapterStatus status, WGPUAdapter adapter, String message) {
    }

    private void internal_onCallback(int status_addr, long adapter_addr, String message_addr) {
        WGPURequestAdapterStatus status_addr_enum = WGPURequestAdapterStatus.CUSTOM.setValue(status_addr);
        WGPURequestAdapterStatus[] status_addr_enum_values = WGPURequestAdapterStatus.values();
        for (int i = 0; i < status_addr_enum_values.length; i++) {
            WGPURequestAdapterStatus enumVal = status_addr_enum_values[i];
            if (enumVal != WGPURequestAdapterStatus.CUSTOM && enumVal.getValue() == status_addr) {
                status_addr_enum = status_addr_enum_values[i];
                break;
            }
        }
        WGPUAdapter adapter_addr_new = WGPUAdapter.native_new();
        adapter_addr_new.internal_reset(adapter_addr, true);
        onCallback(status_addr_enum, adapter_addr_new, message_addr);
    }

    public static native long internal_native_create_addr();
}
