/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;
import com.github.xpenatan.jparser.idl.helper.IDLString;

public class WGPUStringView extends IDLBase {

    static public final WGPUStringView NULL = WGPUStringView.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUStringView(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUStringView native_new() {
        return new WGPUStringView((byte) 0, (char) 0);
    }

    public IDLString getString() {
        return null;
    }
}
