/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLEnum;

public enum WGPUWGSLLanguageFeatureName implements IDLEnum<WGPUWGSLLanguageFeatureName> {

    CUSTOM(0),
    ReadonlyAndReadwriteStorageTextures(WGPUWGSLLanguageFeatureName_ReadonlyAndReadwriteStorageTextures_NATIVE()),
    Packed4x8IntegerDotProduct(WGPUWGSLLanguageFeatureName_Packed4x8IntegerDotProduct_NATIVE()),
    UnrestrictedPointerParameters(WGPUWGSLLanguageFeatureName_UnrestrictedPointerParameters_NATIVE()),
    PointerCompositeAccess(WGPUWGSLLanguageFeatureName_PointerCompositeAccess_NATIVE()),
    Force32(WGPUWGSLLanguageFeatureName_Force32_NATIVE());

    private int value;

    private WGPUWGSLLanguageFeatureName(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUWGSLLanguageFeatureName setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUWGSLLanguageFeatureName getCustom() {
        return CUSTOM;
    }

    /*[-JNI;-NATIVE]
return (jlong)WGPUWGSLLanguageFeatureName_ReadonlyAndReadwriteStorageTextures;
*/
    private static native int WGPUWGSLLanguageFeatureName_ReadonlyAndReadwriteStorageTextures_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUWGSLLanguageFeatureName_Packed4x8IntegerDotProduct;
*/
    private static native int WGPUWGSLLanguageFeatureName_Packed4x8IntegerDotProduct_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUWGSLLanguageFeatureName_UnrestrictedPointerParameters;
*/
    private static native int WGPUWGSLLanguageFeatureName_UnrestrictedPointerParameters_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUWGSLLanguageFeatureName_PointerCompositeAccess;
*/
    private static native int WGPUWGSLLanguageFeatureName_PointerCompositeAccess_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUWGSLLanguageFeatureName_Force32;
*/
    private static native int WGPUWGSLLanguageFeatureName_Force32_NATIVE();
}
