/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.webgpu;

import com.github.xpenatan.webgpu.idl.IDLBase;

public class WGPUProgrammableStageDescriptor extends IDLBase {

    static public final WGPUProgrammableStageDescriptor NULL = WGPUProgrammableStageDescriptor.native_new();

    static public final WGPUProgrammableStageDescriptor T_01 = WGPUProgrammableStageDescriptor.native_new();

    static public final WGPUProgrammableStageDescriptor T_02 = WGPUProgrammableStageDescriptor.native_new();

    static public final WGPUProgrammableStageDescriptor T_03 = WGPUProgrammableStageDescriptor.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUProgrammableStageDescriptor(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUProgrammableStageDescriptor native_new() {
        return new WGPUProgrammableStageDescriptor((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
JGPU::WGPUProgrammableStageDescriptor* nativeObject = (JGPU::WGPUProgrammableStageDescriptor*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public void setNextInChain(WGPUChainedStruct chainedStruct) {
        internal_native_SetNextInChain(native_address, chainedStruct.native_address);
    }

    /*[-JNI;-NATIVE]
JGPU::WGPUProgrammableStageDescriptor* nativeObject = (JGPU::WGPUProgrammableStageDescriptor*)this_addr;
nativeObject->SetNextInChain((JGPU::WGPUChainedStruct* )chainedStruct_addr);
*/
    public static native void internal_native_SetNextInChain(long this_addr, long chainedStruct_addr);

    public void setModule(WGPUShaderModule shaderModule) {
        internal_native_SetModule(native_address, shaderModule.native_address);
    }

    /*[-JNI;-NATIVE]
JGPU::WGPUProgrammableStageDescriptor* nativeObject = (JGPU::WGPUProgrammableStageDescriptor*)this_addr;
nativeObject->SetModule((JGPU::WGPUShaderModule* )shaderModule_addr);
*/
    public static native void internal_native_SetModule(long this_addr, long shaderModule_addr);

    public void setEntryPoint(String entryPoint) {
        internal_native_SetEntryPoint(native_address, entryPoint);
    }

    /*[-JNI;-NATIVE]
JGPU::WGPUProgrammableStageDescriptor* nativeObject = (JGPU::WGPUProgrammableStageDescriptor*)this_addr;
nativeObject->SetEntryPoint(entryPoint);
*/
    public static native void internal_native_SetEntryPoint(long this_addr, String entryPoint);

    public void setConstants(WGPUVectorConstantEntry values) {
        internal_native_SetConstants(native_address, values.native_address);
    }

    /*[-JNI;-NATIVE]
JGPU::WGPUProgrammableStageDescriptor* nativeObject = (JGPU::WGPUProgrammableStageDescriptor*)this_addr;
nativeObject->SetConstants((WGPUVectorConstantEntry* )values_addr);
*/
    public static native void internal_native_SetConstants(long this_addr, long values_addr);
}
