/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;

public class WGPUBlendState extends IDLBase {

    static public final WGPUBlendState NULL = WGPUBlendState.native_new();

    public WGPUBlendState() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUBlendState(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUBlendState native_new() {
        return new WGPUBlendState((byte) 0, (char) 0);
    }

    public WGPUBlendComponent getColor() {
        return null;
    }

    public WGPUBlendComponent getAlpha() {
        return null;
    }

    public static WGPUBlendState obtain() {
        return null;
    }
}
