/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLEnum;

public enum WGPUIndexFormat implements IDLEnum<WGPUIndexFormat> {

    CUSTOM(0), Undefined(WGPUIndexFormat_Undefined_NATIVE()), Uint16(WGPUIndexFormat_Uint16_NATIVE()), Uint32(WGPUIndexFormat_Uint32_NATIVE()), Force32(WGPUIndexFormat_Force32_NATIVE());

    private int value;

    private WGPUIndexFormat(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUIndexFormat setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUIndexFormat getCustom() {
        return CUSTOM;
    }

    private static native int WGPUIndexFormat_Undefined_NATIVE();

    private static native int WGPUIndexFormat_Uint16_NATIVE();

    private static native int WGPUIndexFormat_Uint32_NATIVE();

    private static native int WGPUIndexFormat_Force32_NATIVE();
}
