/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;

public class WGPUSamplerBindingLayout extends IDLBase {

    static public final WGPUSamplerBindingLayout NULL = WGPUSamplerBindingLayout.native_new();

    public WGPUSamplerBindingLayout() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUSamplerBindingLayout(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUSamplerBindingLayout native_new() {
        return new WGPUSamplerBindingLayout((byte) 0, (char) 0);
    }

    public void setNextInChain(WGPUChainedStruct chainedStruct) {
    }

    public void setType(WGPUSamplerBindingType type) {
    }

    public static WGPUSamplerBindingLayout obtain() {
        return null;
    }
}
