/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.webgpu;

import java.util.Map;
import java.util.HashMap;
import com.github.xpenatan.jParser.idl.IDLEnum;

public enum WGPUTextureSampleType implements IDLEnum<WGPUTextureSampleType> {

    CUSTOM(0),
    BindingNotUsed(WGPUTextureSampleType_BindingNotUsed_NATIVE()),
    Undefined(WGPUTextureSampleType_Undefined_NATIVE()),
    Float(WGPUTextureSampleType_Float_NATIVE()),
    UnfilterableFloat(WGPUTextureSampleType_UnfilterableFloat_NATIVE()),
    Depth(WGPUTextureSampleType_Depth_NATIVE()),
    Sint(WGPUTextureSampleType_Sint_NATIVE()),
    Uint(WGPUTextureSampleType_Uint_NATIVE()),
    Force32(WGPUTextureSampleType_Force32_NATIVE());

    private int value;

    private WGPUTextureSampleType(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public WGPUTextureSampleType setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public WGPUTextureSampleType getCustom() {
        return CUSTOM;
    }

    public static final Map<Integer, WGPUTextureSampleType> MAP = new HashMap<>();

    static {
        for (WGPUTextureSampleType value : values()) {
            if (value != CUSTOM) {
                MAP.put(value.value, value);
            }
        }
    }

    /*[-JNI;-NATIVE]
return (jlong)WGPUTextureSampleType_BindingNotUsed;
*/
    private static native int WGPUTextureSampleType_BindingNotUsed_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUTextureSampleType_Undefined;
*/
    private static native int WGPUTextureSampleType_Undefined_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUTextureSampleType_Float;
*/
    private static native int WGPUTextureSampleType_Float_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUTextureSampleType_UnfilterableFloat;
*/
    private static native int WGPUTextureSampleType_UnfilterableFloat_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUTextureSampleType_Depth;
*/
    private static native int WGPUTextureSampleType_Depth_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUTextureSampleType_Sint;
*/
    private static native int WGPUTextureSampleType_Sint_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUTextureSampleType_Uint;
*/
    private static native int WGPUTextureSampleType_Uint_NATIVE();

    /*[-JNI;-NATIVE]
return (jlong)WGPUTextureSampleType_Force32;
*/
    private static native int WGPUTextureSampleType_Force32_NATIVE();
}
