/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;

public class WGPUSurfaceConfiguration extends IDLBase {

    static public final WGPUSurfaceConfiguration NULL = WGPUSurfaceConfiguration.native_new();

    public WGPUSurfaceConfiguration() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUSurfaceConfiguration(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUSurfaceConfiguration native_new() {
        return new WGPUSurfaceConfiguration((byte) 0, (char) 0);
    }

    public void setNextInChain(WGPUChainedStruct chainedStruct) {
    }

    public void setWidth(int width) {
    }

    public void setHeight(int height) {
    }

    public void setFormat(WGPUTextureFormat format) {
    }

    public void setViewFormats(WGPUVectorTextureFormat formats) {
    }

    public void setUsage(WGPUTextureUsage usage) {
    }

    public void setDevice(WGPUDevice device) {
    }

    public void setPresentMode(WGPUPresentMode presentMode) {
    }

    public void setAlphaMode(WGPUCompositeAlphaMode alphaMode) {
    }

    public static WGPUSurfaceConfiguration obtain() {
        return null;
    }
}
