/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;

public class WGPUVectorBindGroupLayout extends IDLBase {

    static public final WGPUVectorBindGroupLayout NULL = WGPUVectorBindGroupLayout.native_new();

    public WGPUVectorBindGroupLayout() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUVectorBindGroupLayout(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUVectorBindGroupLayout native_new() {
        return new WGPUVectorBindGroupLayout((byte) 0, (char) 0);
    }

    public int size() {
        return 0;
    }

    public void clear() {
    }

    public void push_back(WGPUBindGroupLayout groupLayout) {
    }

    public static WGPUVectorBindGroupLayout obtain() {
        return null;
    }
}
