/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;

public class WGPUBindGroupDescriptor extends IDLBase {

    static public final WGPUBindGroupDescriptor NULL = WGPUBindGroupDescriptor.native_new();

    public WGPUBindGroupDescriptor() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUBindGroupDescriptor(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUBindGroupDescriptor native_new() {
        return new WGPUBindGroupDescriptor((byte) 0, (char) 0);
    }

    public void setLabel(String value) {
    }

    public void setNextInChain(WGPUChainedStruct chainedStruct) {
    }

    public void setLayout(WGPUBindGroupLayout layout) {
    }

    public void setEntries(WGPUVectorBindGroupEntry entries) {
    }

    public static WGPUBindGroupDescriptor obtain() {
        return null;
    }
}
