/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.webgpu;

import com.github.xpenatan.jParser.idl.IDLBase;

public class WGPUVectorWGPUInstanceLimits extends IDLBase {

    static public final WGPUVectorWGPUInstanceLimits NULL = WGPUVectorWGPUInstanceLimits.native_new();

    public WGPUVectorWGPUInstanceLimits() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUVectorWGPUInstanceLimits(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUVectorWGPUInstanceLimits native_new() {
        return new WGPUVectorWGPUInstanceLimits((byte) 0, (char) 0);
    }

    public int size() {
        return 0;
    }

    public void clear() {
    }

    public void push_back(WGPUInstanceLimits featureName) {
    }

    public static WGPUVectorWGPUInstanceLimits obtain() {
        return null;
    }
}
