/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/
package com.github.xpenatan.webgpu;

import com.github.xpenatan.webgpu.idl.IDLBase;

public class WGPUVertexState extends IDLBase {

    static public final WGPUVertexState NULL = WGPUVertexState.native_new();

    static public final WGPUVertexState T_01 = WGPUVertexState.native_new();

    static public final WGPUVertexState T_02 = WGPUVertexState.native_new();

    static public final WGPUVertexState T_03 = WGPUVertexState.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WGPUVertexState(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static WGPUVertexState native_new() {
        return new WGPUVertexState((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*[-JNI;-NATIVE]
JGPU::WGPUVertexState* nativeObject = (JGPU::WGPUVertexState*)this_addr;
delete nativeObject;
*/
    public static native void internal_native_deleteNative(long this_addr);

    public void setNextInChain(WGPUChainedStruct chainedStruct) {
        internal_native_SetNextInChain(native_address, chainedStruct.native_address);
    }

    /*[-JNI;-NATIVE]
JGPU::WGPUVertexState* nativeObject = (JGPU::WGPUVertexState*)this_addr;
nativeObject->SetNextInChain((JGPU::WGPUChainedStruct* )chainedStruct_addr);
*/
    public static native void internal_native_SetNextInChain(long this_addr, long chainedStruct_addr);

    public void setModule(WGPUShaderModule shaderModule) {
        internal_native_SetModule(native_address, shaderModule.native_address);
    }

    /*[-JNI;-NATIVE]
JGPU::WGPUVertexState* nativeObject = (JGPU::WGPUVertexState*)this_addr;
nativeObject->SetModule((JGPU::WGPUShaderModule* )shaderModule_addr);
*/
    public static native void internal_native_SetModule(long this_addr, long shaderModule_addr);

    public void setEntryPoint(String entryPoint) {
        internal_native_SetEntryPoint(native_address, entryPoint);
    }

    /*[-JNI;-NATIVE]
JGPU::WGPUVertexState* nativeObject = (JGPU::WGPUVertexState*)this_addr;
nativeObject->SetEntryPoint(entryPoint);
*/
    public static native void internal_native_SetEntryPoint(long this_addr, String entryPoint);

    public void setConstants(WGPUVectorConstantEntry constants) {
        internal_native_SetConstants(native_address, constants.native_address);
    }

    /*[-JNI;-NATIVE]
JGPU::WGPUVertexState* nativeObject = (JGPU::WGPUVertexState*)this_addr;
nativeObject->SetConstants((WGPUVectorConstantEntry* )constants_addr);
*/
    public static native void internal_native_SetConstants(long this_addr, long constants_addr);

    public void setBuffers(WGPUVectorVertexBufferLayout buffers) {
        internal_native_SetBuffers(native_address, buffers.native_address);
    }

    /*[-JNI;-NATIVE]
JGPU::WGPUVertexState* nativeObject = (JGPU::WGPUVertexState*)this_addr;
nativeObject->SetBuffers((WGPUVectorVertexBufferLayout* )buffers_addr);
*/
    public static native void internal_native_SetBuffers(long this_addr, long buffers_addr);
}
