name: Build Dawn

on:
  workflow_dispatch:
  workflow_call:

env:
  CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
  CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
  SIGNING_KEY: ${{ secrets.PGP_SECRET }}
  SIGNING_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      - name: Set up MinGW
        uses: msys2/setup-msys2@v2

      - name: Set up Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Append the directory of 'vcvarsall.bat' to PATH environment variable
        uses: myci-actions/export-env-var-powershell@1
        with:
          name: PATH
          value: $env:PATH;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build

      - name: Download sources
        run: ./gradlew :webgpu:webgpu-dawn:download_source

      - name: Generate cmake
        run: ./gradlew :webgpu:webgpu-dawn:generateCMake_windows_x64

      - name: Build Dawn
        run: ./gradlew :webgpu:webgpu-dawn:build_windows_x64

      - name: Install Dawn
        run: ./gradlew :webgpu:webgpu-dawn:build_windows_x64_install
