name: Build Dawn

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      - name: Set up MinGW
        uses: msys2/setup-msys2@v2

      - name: Set up Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Append the directory of 'vcvarsall.bat' to PATH environment variable
        uses: myci-actions/export-env-var-powershell@1
        with:
          name: PATH
          value: $env:PATH;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build

      - name: Download sources
        run: ./gradlew :webgpu:webgpu-dawn:download_source

      - name: Generate cmake
        run: ./gradlew :webgpu:webgpu-dawn:generateCMake_windows_x64_static

      - name: Build Dawn static
        run: ./gradlew :webgpu:webgpu-dawn:build_windows_x64

      - name: Upload natives static
        uses: actions/upload-artifact@v4
        with:
          name: windows_x64_static
          path: ./webgpu/webgpu-dawn/build/dawn/install/

      - name: Delete path
        run: rm -rf ./webgpu/webgpu-dawn/build/dawn/install/
        shell: bash

      - name: Generate cmake
        run: ./gradlew :webgpu:webgpu-dawn:generateCMake_windows_x64_shared

      - name: Build Dawn shared
        run: ./gradlew :webgpu:webgpu-dawn:build_windows_x64

      - name: Upload natives shared
        uses: actions/upload-artifact@v4
        with:
          name: windows_x64_shared
          path: ./webgpu/webgpu-dawn/build/dawn/install/

  build_macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      - name: Install CMake and Ninja
        run: |
          brew install cmake ninja

      - name: Download sources
        run: ./gradlew :webgpu:webgpu-dawn:download_source

      - name: Generate CMake static
        run: ./gradlew :webgpu:webgpu-dawn:generateCMake_macos_x64_static

      - name: Build Dawn static
        run: ./gradlew :webgpu:webgpu-dawn:build_macos_x64

      - name: Upload natives static
        uses: actions/upload-artifact@v4
        with:
          name: macos_x64_static
          path: ./webgpu/webgpu-dawn/build/dawn/install/

      - name: Delete path
        run: rm -rf ./webgpu/webgpu-dawn/build/dawn/install/
        shell: bash

      - name: Generate CMake (shared)
        run: ./gradlew :webgpu:webgpu-dawn:generateCMake_macos_x64_shared

      - name: Build Dawn shared
        run: ./gradlew :webgpu:webgpu-dawn:build_macos_x64

      - name: Upload natives shared
        uses: actions/upload-artifact@v4
        with:
          name: macos_x64_shared
          path: ./webgpu/webgpu-dawn/build/dawn/install/

    build_linux:
      name: Build Linux
      runs-on: ubuntu-latest
      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.12.1
          with:
            access_token: ${{ github.token }}

        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: "corretto"
            java-version: 17

        - name: Install CMake, Ninja, and dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y cmake ninja-build libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev

        - name: Download sources
          run: ./gradlew :webgpu:webgpu-dawn:download_source

        - name: Generate CMake (static)
          run: ./gradlew :webgpu:webgpu-dawn:generateCMake_linux_x64_static

        - name: Build Dawn static
          run: ./gradlew :webgpu:webgpu-dawn:build_linux_x64

        - name: Upload natives static
          uses: actions/upload-artifact@v4
          with:
            name: linux_x64_static
            path: ./webgpu/webgpu-dawn/build/dawn/install/

        - name: Delete path
          run: rm -rf ./webgpu/webgpu-dawn/build/dawn/install/
          shell: bash

        - name: Generate CMake shared
          run: ./gradlew :webgpu:webgpu-dawn:generateCMake_linux_x64_shared

        - name: Build Dawn shared
          run: ./gradlew :webgpu:webgpu-dawn:build_linux_x64

        - name: Upload natives shared
          uses: actions/upload-artifact@v4
          with:
            name: linux_x64_shared
            path: ./webgpu/webgpu-dawn/build/dawn/install/

  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      - name: Set up Android NDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: '26.1.10909125'

      - name: Install CMake and Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Download sources
        run: ./gradlew :webgpu:webgpu-dawn:download_source

      - name: Generate CMake (static)
        run: ./gradlew :webgpu:webgpu-dawn:generateCMake_android_arm64_static
        env:
          ANDROID_NDK: ${{ env.ANDROID_NDK_HOME }}

      - name: Build Dawn static
        run: ./gradlew :webgpu:webgpu-dawn:build_android_arm64

      - name: Upload natives static
        uses: actions/upload-artifact@v4
        with:
          name: android_arm64_static
          path: ./webgpu/webgpu-dawn/build/dawn/install/

      - name: Delete path
        run: rm -rf ./webgpu/webgpu-dawn/build/dawn/install/
        shell: bash

      - name: Generate CMake shared
        run: ./gradlew :webgpu:webgpu-dawn:generateCMake_android_arm64_shared
        env:
          ANDROID_NDK: ${{ env.ANDROID_NDK_HOME }}

      - name: Build Dawn shared
        run: ./gradlew :webgpu:webgpu-dawn:build_android_arm64

      - name: Upload natives shared
        uses: actions/upload-artifact@v4
        with:
          name: android_arm64_shared
          path: ./webgpu/webgpu-dawn/build/dawn/install/

  build_ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      - name: Install CMake and Ninja
        run: |
          brew install cmake ninja

      - name: Download sources
        run: ./gradlew :webgpu:webgpu-dawn:download_source

      - name: Generate CMake static
        run: ./gradlew :webgpu:webgpu-dawn:generateCMake_ios_arm64_static

      - name: Build Dawn static
        run: ./gradlew :webgpu:webgpu-dawn:build_ios_arm64

      - name: Upload natives static
        uses: actions/upload-artifact@v4
        with:
          name: ios_arm64_static
          path: ./webgpu/webgpu-dawn/build/dawn/install/

      - name: Delete path
        run: rm -rf ./webgpu/webgpu-dawn/build/dawn/install/
        shell: bash

      - name: Generate CMake (shared)
        run: ./gradlew :webgpu:webgpu-dawn:generateCMake_ios_arm64_shared

      - name: Build Dawn shared
        run: ./gradlew :webgpu:webgpu-dawn:build_ios_arm64

      - name: Upload natives shared
        uses: actions/upload-artifact@v4
        with:
          name: ios_arm64_shared
          path: ./webgpu/webgpu-dawn/build/dawn/install/