name: Build Dawn

on:
  workflow_dispatch:

jobs:
  windows_x64:
    name: Windows x64
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: "corretto"
          java-version: 25

      - name: Set up Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64

      - name: Download Dawn source
        run: ./gradlew :webgpu:dawn:download_source

      - name: Generate CMake
        run: ./gradlew :webgpu:dawn:generate_cmake_windows_x64_static_release

      - name: Build
        run: ./gradlew :webgpu:dawn:build_windows_x64

      - name: Upload Dawn
        uses: actions/upload-artifact@v7
        with:
          name: dawn-windows-x64
          path: ./webgpu/dawn/build/dawn/install/build_windows_x64

  mac_x64:
    name: macOS x64
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: "corretto"
          java-version: 25

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Download Dawn source
        run: ./gradlew :webgpu:dawn:download_source

      - name: Generate CMake
        run: ./gradlew :webgpu:dawn:generate_cmake_mac_x64_static_release

      - name: Build
        run: ./gradlew :webgpu:dawn:build_mac_x64

      - name: Upload Dawn
        uses: actions/upload-artifact@v7
        with:
          name: dawn-mac-x64
          path: ./webgpu/dawn/build/dawn/install/build_mac_x64

  mac_arm64:
    name: macOS arm64
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: "corretto"
          java-version: 25

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Download Dawn source
        run: ./gradlew :webgpu:dawn:download_source

      - name: Generate CMake
        run: ./gradlew :webgpu:dawn:generate_cmake_mac_arm64_static_release

      - name: Build
        run: ./gradlew :webgpu:dawn:build_mac_arm64

      - name: Upload Dawn
        uses: actions/upload-artifact@v7
        with:
          name: dawn-mac-arm64
          path: ./webgpu/dawn/build/dawn/install/build_mac_arm64
